"""Core Paper 1 decks: problem solving, programming, emerging issues, legislation."""

CP1 = "01-core-component/01-core-paper-1.md"
NOTATION = "03-appendices/02-flowchart-and-python-notation.md"

DECKS = [
    {
        "area": "core",
        "file": "core/01-computational-thinking-and-algorithms.pptx",
        "title": "Computational Thinking and Algorithms",
        "unit": "Core Paper 1",
        "spec": "1.1, 1.2",
        "pages": [CP1, NOTATION],
        "objectives": [
            "Describe the four components of computational thinking and when to use each.",
            "Express an algorithm as a flowchart, a written description and code.",
            "Determine an algorithm's purpose and output, and correct errors in it.",
            "Translate an algorithm between notations.",
        ],
        "starter": "Write instructions for making a cup of tea for someone who has never been in a kitchen. "
                   "What did you have to break down? What did you leave out?",
        "slides": [
            {"type": "cards", "title": "The four components of computational thinking",
             "cards": [
                 ("Decomposition", "Break a problem or solution into smaller, manageable parts. Show it with block "
                  "diagrams, flowcharts, code or written descriptions."),
                 ("Pattern recognition", "Spot similarities within and between problems, and reuse solutions that "
                  "worked before."),
                 ("Abstraction", "Keep only what matters: the inputs, outputs, what varies, what stays constant "
                  "and the key repeated actions."),
                 ("Algorithmic design", "Express the solution as clear, ordered steps a computer can follow."),
             ],
             "notes": "Link to the starter: the steps students grouped were decomposition; the details they skipped "
                      "were abstraction."},
            {"type": "compare", "title": "Weighing up computational thinking",
             "left": ("Benefits", [
                 "Large problems become manageable pieces",
                 "Parts can be built and tested separately",
                 "Reusing patterns saves development time",
                 "Abstraction focuses effort on what matters",
             ]),
             "right": ("Drawbacks", [
                 "Decomposing takes time up front",
                 "Over-abstraction can hide an important detail",
                 "A false pattern leads to the wrong solution",
                 "Parts still have to be integrated",
             ])},
            {"type": "table", "title": "Three ways to express an algorithm",
             "header": ["Notation", "Benefit", "Drawback"],
             "widths": [2, 3.5, 3.5],
             "rows": [
                 ["Flowchart", "Visual; easy to follow the flow and decisions", "Slow to draw and edit for big problems"],
                 ["Written description", "Quick to write; hierarchical markers show order", "Can be ambiguous"],
                 ["Code", "Precise and can be run and tested", "Needs programming knowledge to read"],
             ],
             "notes": "Flowchart symbols: terminator, process, sub-process, decision, input/output, arrows and labels. "
                      "The full list is on the Flowchart and Python notation page."},
            {"type": "cards", "title": "Actions that control the order of steps",
             "cards": [
                 ("Sequence", "Steps run one after another, in order."),
                 ("Selection", "A condition chooses which path to take: if, elif, else, match case."),
                 ("Iteration", "Steps repeat: a for loop a set number of times, a while loop until a condition changes."),
             ]},
            {"type": "bullets", "title": "Working with algorithms",
             "bullets": [
                 "Purpose: work out what an algorithm is for by tracing it with sample inputs.",
                 "Output: predict exactly what it will output for a given input.",
                 "Errors: find and correct logic errors, e.g. a wrong comparison or a loop that never ends.",
                 "Translate: turn a flowchart into code, or code into a written description.",
                 "Design: build your own algorithm using sequence, selection and iteration.",
             ],
             "callout": "Use a trace table: one column per variable, one row per step. It shows exactly where an "
                        "algorithm goes wrong."},
        ],
        "quiz": [
            ("Name the four components of computational thinking.",
             "Decomposition, pattern recognition, abstraction, algorithmic design."),
            ("Which flowchart symbol shows a decision?", "A diamond."),
            ("Which Python keyword gives condition-controlled iteration?", "while."),
            ("Give one benefit of expressing an algorithm as code.", "It is precise and can be run and tested."),
            ("What is a trace table used for?", "Recording variable values step by step to check or debug an algorithm."),
        ],
        "activity": {
            "title": "Flowchart to Python",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Draw a flowchart that asks for exam marks until the user enters -1, then outputs the average.",
                "Trace it with the inputs 60, 80, -1.",
                "Translate the flowchart into Python.",
                "Swap code with another pair and find one improvement.",
            ],
            "success": [
                "Correct flowchart symbols",
                "Loop ends on -1 without counting it",
                "Code matches the flowchart",
                "Trace gives an average of 70",
            ],
        },
        "exit": [
            "Which component of computational thinking helps most when a problem is huge?",
            "When would a flowchart be better than code?",
            "What is the difference between a for loop and a while loop?",
        ],
    },
    {
        "area": "core",
        "file": "core/02-problem-solving-strategies.pptx",
        "title": "Problem-Solving Strategies",
        "unit": "Core Paper 1",
        "spec": "1.3",
        "pages": [CP1],
        "objectives": [
            "Compare top-down, bottom-up and modular approaches.",
            "Use root cause analysis: five whys, FMEA and event tree analysis.",
            "Apply the high-level problem-solving strategy to a software problem.",
        ],
        "starter": "Your app crashes every time a user uploads a photo. What would you do first, and why?",
        "slides": [
            {"type": "cards", "title": "Three approaches",
             "cards": [
                 ("Top-down", "Start with the whole problem and break it into smaller parts. Good when the brief is clear."),
                 ("Bottom-up", "Start with small, working components and combine them. Good when reliable parts exist."),
                 ("Modularisation", "Split the solution into self-contained modules that can be built, tested and reused separately."),
             ]},
            {"type": "cards", "title": "Root cause analysis",
             "cards": [
                 ("Five whys", "Keep asking 'why?' until you reach the underlying cause, not just the symptom."),
                 ("FMEA", "Failure Mode and Effects Analysis lists every way a component could fail and the effect of each."),
                 ("Event tree analysis", "Starts from one event and maps every outcome that could follow."),
                 ("Then act", "Log it, close it, or escalate it to a manager, specialist or third party."),
             ],
             "notes": "Five whys example: the upload crashes. Why? The file is too big. Why? No size check. Why? "
                      "Validation was never specified. Why? Requirements missed non-functional limits."},
            {"type": "process", "title": "The high-level problem-solving strategy",
             "steps": [
                 ("Define", "State exactly what the problem is."),
                 ("Gather", "Collect information, error logs, user reports."),
                 ("Analyse", "Look for the cause and patterns."),
                 ("Plan", "Decide on a plan of action."),
                 ("Implement", "Write and apply the fix."),
                 ("Review", "Test that it works and nothing else broke."),
             ]},
        ],
        "quiz": [
            ("Which approach builds a solution from small working components?", "Bottom-up."),
            ("What is the aim of the five whys?", "To find the underlying root cause rather than the symptom."),
            ("What does FMEA stand for?", "Failure Mode and Effects Analysis."),
            ("What is the last step of the problem-solving strategy?", "Review the solution."),
        ],
        "activity": {
            "title": "Root cause a bug",
            "time": "20 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: an online shop charges some customers twice.",
                "Use the five whys to reach a believable root cause.",
                "Decide whether to log, close or escalate it.",
                "Plan the fix using the six-step strategy.",
            ],
            "success": [
                "Each 'why' follows from the last",
                "Root cause is a cause, not a symptom",
                "Plan covers testing and review",
            ],
        },
        "exit": [
            "When would you choose bottom-up over top-down?",
            "Why does fixing a symptom not solve the problem?",
            "Why must a fix be reviewed?",
        ],
    },
    {
        "area": "core",
        "file": "core/03-data-types-variables-and-data-structures.pptx",
        "title": "Data Types, Variables and Data Structures",
        "unit": "Core Paper 1",
        "spec": "2.1, 2.2, 2.3",
        "pages": [CP1, NOTATION],
        "objectives": [
            "Choose the right standard data type for a value.",
            "Declare and use variables and constants, and explain scope.",
            "Use type conversion functions.",
            "Choose and use lists, arrays and dictionaries.",
        ],
        "starter": "What data type would you use for: a phone number, a price, whether a user is logged in? "
                   "Careful with the phone number.",
        "slides": [
            {"type": "table", "title": "Standard data types",
             "header": ["Type", "Holds", "Python example"],
             "widths": [1.5, 3.5, 3.5],
             "rows": [
                 ["Integer", "Whole numbers", "age = 17"],
                 ["Float", "Numbers with a decimal part", "price = 4.99"],
                 ["String", "Text, including digits with no maths meaning", "phone = '07700900123'"],
                 ["Boolean", "True or False", "logged_in = True"],
             ],
             "notes": "Phone numbers are strings: they can start with 0 and you never do maths on them."},
            {"type": "compare", "title": "Variables and constants",
             "left": ("Variable", [
                 "A named value that can change while the program runs",
                 "score = score + 10",
             ]),
             "right": ("Constant", [
                 "A named value that should not change",
                 "Python convention: capitals, e.g. VAT_RATE = 0.2",
                 "Makes code easier to read and update",
             ])},
            {"type": "compare", "title": "Scope and conversion",
             "left": ("Scope", [
                 "Local: created inside a function, only usable there",
                 "Global: created outside functions, usable anywhere",
                 "Prefer local variables: fewer side effects",
             ]),
             "right": ("Type conversion functions", [
                 "int('42') gives 42",
                 "float('3.5') gives 3.5",
                 "str(99) gives '99'",
                 "bool(0) gives False",
                 "input() always returns a string",
             ])},
            {"type": "table", "title": "Data structures",
             "header": ["Structure", "What it is", "Use it for"],
             "widths": [1.5, 3.8, 3.4],
             "rows": [
                 ["List", "Ordered, changeable collection: scores = [12, 7, 9]", "A group of items you add to or sort"],
                 ["Array", "Ordered collection of items of the same type", "Fixed sets of values, e.g. sensor readings"],
                 ["Dictionary", "Key and value pairs: user = {'name': 'Ali', 'age': 17}", "Looking values up by a key"],
             ],
             "caption": "Useful list methods: append(), insert(), remove(), pop(), sort(), index(), count(), len(), in."},
        ],
        "quiz": [
            ("What data type should store a price?", "Float."),
            ("What does input() always return?", "A string."),
            ("What is a local variable?", "A variable created inside a function and only usable there."),
            ("How do you add an item to the end of a list?", "list.append(item)."),
            ("When is a dictionary better than a list?", "When you need to look values up by a key."),
        ],
        "activity": {
            "title": "Build a gradebook",
            "time": "25 minutes",
            "format": "Individual, in Python",
            "steps": [
                "Create a dictionary mapping five student names to a list of marks.",
                "Ask the user for a name and a new mark, converting the input correctly.",
                "Append the mark to that student's list.",
                "Output each student's highest mark using max().",
            ],
            "success": [
                "Correct data types used",
                "Input is converted with int()",
                "Unknown names handled",
                "Output is clearly labelled",
            ],
        },
        "exit": [
            "Why should a postcode be a string?",
            "Give one reason to use a constant.",
            "Name two list methods and what they do.",
        ],
    },
    {
        "area": "core",
        "file": "core/04-operators-input-output-and-program-flow.pptx",
        "title": "Operators, Input, Output and Program Flow",
        "unit": "Core Paper 1",
        "spec": "2.4, 2.5, 2.6",
        "pages": [CP1, NOTATION],
        "objectives": [
            "Use arithmetic, relational and Boolean operators.",
            "Implement input and output with the keyboard, screen and text files.",
            "Use sequence, selection and count and condition-controlled loops.",
        ],
        "starter": "What does 17 // 5 give in Python? What about 17 % 5? Guess, then we will check.",
        "slides": [
            {"type": "table", "title": "Operators",
             "header": ["Type", "Operators", "Example"],
             "widths": [1.6, 3.5, 3.5],
             "rows": [
                 ["Arithmetic", "+  -  *  /  **  //  %", "17 // 5 is 3; 17 % 5 is 2; 2 ** 3 is 8"],
                 ["Relational", "==  !=  <  >  <=  >=", "age >= 18"],
                 ["Boolean", "not  and  or", "age >= 18 and has_id"],
             ],
             "notes": "// is integer division, % is modulus (the remainder), ** is exponentiation."},
            {"type": "process", "title": "Working with text files",
             "steps": [
                 ("Open", "open('scores.txt', 'r') to read, 'w' to write, 'a' to append."),
                 ("Read or write", "read(), readline(), readlines(), or write()."),
                 ("Process", "line.strip() and line.split(',') to tidy and split each line."),
                 ("Close", "close() so data is saved and the file is released."),
             ]},
            {"type": "cards", "title": "Selection",
             "cards": [
                 ("if / elif / else", "Checks conditions in order and runs the first block that is True."),
                 ("match case", "Compares one value against several patterns. Tidy for menus."),
                 ("try except", "Catches errors, e.g. when a user types letters instead of a number."),
             ]},
            {"type": "compare", "title": "Iteration",
             "left": ("Count-controlled: for", [
                 "Repeats a known number of times",
                 "for i in range(10):",
                 "Also loops over lists: for name in names:",
                 "Cannot loop forever by mistake",
             ]),
             "right": ("Condition-controlled: while", [
                 "Repeats while a condition is True",
                 "while guess != answer:",
                 "Good when you do not know how many times",
                 "Risk: an infinite loop if the condition never changes",
             ])},
        ],
        "quiz": [
            ("What does 20 % 6 evaluate to?", "2."),
            ("Which operator checks two values are not equal?", "!="),
            ("Which file mode adds to the end of a file without deleting it?", "'a' (append)."),
            ("Which loop suits 'keep asking until the password is right'?", "A while loop."),
            ("Why must a file be closed?", "So data is saved and the file is released."),
        ],
        "activity": {
            "title": "High score table",
            "time": "30 minutes",
            "format": "Individual, in Python",
            "steps": [
                "Write a menu using match case: 1 add score, 2 show scores, 3 quit.",
                "Option 1 appends 'name,score' to scores.txt.",
                "Option 2 reads the file and prints each score using split().",
                "Loop the menu with while until the user quits.",
            ],
            "success": [
                "Menu loops correctly",
                "File opened in the right modes",
                "Output is tidy",
                "Invalid menu options handled",
            ],
        },
        "exit": [
            "What is the difference between / and //?",
            "Why might a while loop never end?",
            "Why use match case instead of many elif statements?",
        ],
    },
    {
        "area": "core",
        "file": "core/05-functions-procedures-and-validation.pptx",
        "title": "Functions, Procedures and Validation",
        "unit": "Core Paper 1",
        "spec": "2.7, 2.8",
        "pages": [CP1],
        "objectives": [
            "Explain the difference between a function and a procedure.",
            "Compare user-written, built-in and library subroutines.",
            "Write validation checks in code.",
        ],
        "starter": "You need to check an email address in five places in your program. Would you copy the code five times? Why not?",
        "slides": [
            {"type": "compare", "title": "Functions and procedures",
             "left": ("Function", [
                 "May take parameters",
                 "Must return a result",
                 "Example: def area(w, h): return w * h",
             ]),
             "right": ("Procedure", [
                 "May take parameters",
                 "Does not return a result",
                 "Example: def greet(name): print('Hello', name)",
             ])},
            {"type": "table", "title": "Where subroutines come from",
             "header": ["Source", "Example", "Trade-off"],
             "widths": [2.2, 3, 3.6],
             "rows": [
                 ["User-written", "def calculate_vat(price):", "Exactly what you need, but you must write and test it"],
                 ["Built into the language", "len(), round(), max()", "Reliable and fast, but general purpose"],
                 ["Language libraries", "math.sqrt(), random.randint()", "Tested and documented; needs an import"],
                 ["Third-party libraries", "pandas, Matplotlib", "Powerful, but adds dependencies and security risk"],
             ]},
            {"type": "table", "title": "Validation checks",
             "header": ["Check", "Makes sure", "Python idea"],
             "widths": [1.5, 3, 4.2],
             "rows": [
                 ["Presence", "Something was entered", "if name != '':"],
                 ["Length", "Right number of characters", "if len(password) >= 8:"],
                 ["Range", "Within limits", "if 1 <= guests <= 8:"],
                 ["Type", "Right data type", "if value.isdigit():"],
                 ["Format", "Matches a pattern", "if '@' in email:"],
                 ["Check digit", "A calculated digit matches", "e.g. ISBN or barcode check"],
             ]},
        ],
        "quiz": [
            ("What must a function do that a procedure does not?", "Return a result."),
            ("Give one drawback of third-party libraries.", "Extra dependencies, or security and maintenance risk."),
            ("Which check makes sure a field is not blank?", "Presence check."),
            ("Write a range check for an age between 11 and 18.", "if 11 <= age <= 18:"),
        ],
        "activity": {
            "title": "Validation library",
            "time": "30 minutes",
            "format": "Pairs, in Python",
            "steps": [
                "Write functions is_present(), is_in_range() and is_valid_email() that return True or False.",
                "Write a procedure that keeps asking for input until every check passes.",
                "Test each function with valid, invalid and boundary data.",
                "Add a docstring to each function.",
            ],
            "success": [
                "Functions return Booleans",
                "No repeated code",
                "Boundaries tested",
            ],
        },
        "exit": [
            "Is print() a function or a procedure in your own code terms, and why?",
            "What does a check digit protect against?",
            "Why reuse a validation function instead of copying code?",
        ],
    },
    {
        "area": "core",
        "file": "core/06-programming-practice-and-robust-code.pptx",
        "title": "Programming Practice and Robust Code",
        "unit": "Core Paper 1",
        "spec": "2.9, 2.10",
        "pages": [CP1],
        "objectives": [
            "Choose a logical order of operations and efficient data structures.",
            "Apply naming conventions and good presentation.",
            "Describe the characteristics of robust code.",
            "Locate and correct errors through debugging.",
        ],
        "starter": "Look at this line: x=a*b+c/d-e. What does it do? Now rewrite it so someone else could understand it.",
        "slides": [
            {"type": "cards", "title": "Design considerations",
             "cards": [
                 ("Logical order", "Put actions in the right order so results are accurate and errors are avoided."),
                 ("Efficiency", "Choose data structures and action order that save execution time and memory."),
                 ("Naming", "Meaningful names in one style: camelCase or snake_case (Python uses snake_case)."),
                 ("Presentation", "Whitespace, indentation and sensible line length make code readable."),
             ],
             "notes": "Students must judge an algorithm on requirements, efficiency, data structures, presentation and maintainability."},
            {"type": "cards", "title": "Characteristics of robust code",
             "cards": [
                 ("Unexpected input", "Validates input and copes with anything a user types."),
                 ("Unexpected termination", "Handles files missing or connections dropping without crashing."),
                 ("Meaningful errors", "Error messages say exactly what went wrong and what to do."),
             ]},
            {"type": "table", "title": "Types of error",
             "header": ["Error", "What happens", "Example"],
             "widths": [1.6, 3.4, 3.6],
             "rows": [
                 ["Syntax", "Code breaks the language rules and will not run", "Missing colon after if"],
                 ["Runtime", "Program crashes while running", "Dividing by zero; opening a missing file"],
                 ["Logic", "Runs, but gives the wrong result", "Using < instead of <="],
             ],
             "caption": "Debugging means locating and correcting errors: read error messages, use print statements, trace tables and IDE breakpoints."},
        ],
        "quiz": [
            ("Which naming style does Python use for variables?", "snake_case."),
            ("Which error type still runs but gives the wrong answer?", "A logic error."),
            ("Name one characteristic of robust code.", "Handles unexpected input, handles unexpected termination, or gives meaningful errors."),
            ("What does a breakpoint do?", "Pauses the program at a line so you can inspect variables."),
        ],
        "activity": {
            "title": "Fix and tidy",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher gives you a short program with poor names and three bugs.",
                "Find and fix each bug, recording its type.",
                "Rename variables and add whitespace and comments.",
                "Add try except so bad input cannot crash it.",
            ],
            "success": [
                "All three bugs fixed and classified",
                "Consistent snake_case names",
                "Program survives bad input",
            ],
            "notes": "Plant one syntax, one runtime and one logic error.",
        },
        "exit": [
            "Why do meaningful error messages matter to users?",
            "Give one way to make code more efficient.",
            "Which debugging technique do you find most useful?",
        ],
    },
    {
        "area": "core",
        "file": "core/07-searching-and-sorting-algorithms.pptx",
        "title": "Searching and Sorting Algorithms",
        "unit": "Core Paper 1",
        "spec": "2.11",
        "pages": [CP1],
        "objectives": [
            "Describe linear and binary search.",
            "Describe bubble, insertion and merge sort.",
            "Compare algorithms using memory, execution time and number of comparisons.",
            "Choose a suitable algorithm for a situation.",
        ],
        "starter": "Find the word 'kiwi' in a dictionary. Did you start at page one? Why not?",
        "slides": [
            {"type": "compare", "title": "Searching",
             "left": ("Linear search", [
                 "Check each item in turn from the start",
                 "Works on unsorted data",
                 "Simple to write",
                 "Slow on large lists: may check every item",
             ]),
             "right": ("Binary search", [
                 "Needs sorted data",
                 "Check the middle; discard the half that cannot contain the target",
                 "Repeat until found or nothing is left",
                 "Very fast on large lists",
             ])},
            {"type": "table", "title": "Sorting algorithms",
             "header": ["Algorithm", "How it works", "Best for"],
             "widths": [1.6, 4.4, 2.6],
             "rows": [
                 ["Bubble sort", "Compare neighbours and swap; repeat passes until no swaps", "Tiny lists, teaching"],
                 ["Insertion sort", "Take each item and insert it into the sorted part", "Small or nearly sorted lists"],
                 ["Merge sort", "Split into single items, then merge pairs back in order", "Large lists; needs extra memory"],
             ]},
            {"type": "cards", "title": "Comparing algorithms",
             "cards": [
                 ("Execution time", "How long it takes as the data grows."),
                 ("Memory use", "Merge sort needs extra memory to merge; bubble and insertion sort in place."),
                 ("Comparisons", "Count how many times items are compared."),
                 ("Best, worst, average", "Bubble sort on sorted data can finish in one pass; reversed data is its worst case."),
             ],
             "notes": "Big O notation is not required, but students must reason about best, worst and average cases."},
        ],
        "quiz": [
            ("What must be true before a binary search?", "The data must be sorted."),
            ("How many items might a linear search check in a list of 1,000?", "Up to 1,000 (every item)."),
            ("Which sort splits a list and merges it back together?", "Merge sort."),
            ("Which sort is efficient on nearly sorted data?", "Insertion sort."),
            ("Give one drawback of merge sort.", "It uses extra memory."),
        ],
        "activity": {
            "title": "Human sorting race",
            "time": "25 minutes",
            "format": "Groups of eight",
            "steps": [
                "Each person holds a number card.",
                "Sort yourselves using bubble sort, counting comparisons.",
                "Shuffle and repeat with insertion sort, then merge sort.",
                "Compare the counts and write a rule for when to use each.",
            ],
            "success": [
                "Each algorithm followed correctly",
                "Comparisons counted",
                "Rule is justified with evidence",
            ],
        },
        "exit": [
            "Why can't binary search work on unsorted data?",
            "What is the worst case for bubble sort?",
            "Which algorithm would you use to sort 1 million records, and why?",
        ],
    },
    {
        "area": "core",
        "file": "core/08-testing.pptx",
        "title": "Testing",
        "unit": "Core Paper 1",
        "spec": "2.12",
        "pages": [CP1],
        "objectives": [
            "Explain why components are tested before integration.",
            "Compare testing methods and when each is used.",
            "Create valid, invalid, boundary and erroneous test data.",
            "Write a structured test plan.",
        ],
        "starter": "A game releases with a bug that deletes save files. At what point should that bug have been caught?",
        "slides": [
            {"type": "table", "title": "Testing methods",
             "header": ["Method", "What it checks"],
             "widths": [2.4, 6],
             "rows": [
                 ["Concept", "Whether an idea is worth building"],
                 ["Unit / integration", "One component alone, then components working together"],
                 ["System / acceptance", "The whole system, then whether it meets the user's needs"],
                 ["Boundary", "Values at the edges of what is allowed"],
                 ["Performance / load / stress", "Speed under normal load, heavy load and beyond its limits"],
                 ["Usability / regression", "How easy it is to use; that changes have not broken old features"],
                 ["Closed box / open box", "Testing without, or with, knowledge of the code"],
             ]},
            {"type": "cards", "title": "Test data",
             "cards": [
                 ("Valid", "Should be accepted. Guests: 4"),
                 ("Invalid", "Right type, should be rejected. Guests: 12"),
                 ("Boundary", "At the edge. Guests: 1 and 8"),
                 ("Erroneous", "Wrong type. Guests: 'four'"),
             ]},
            {"type": "process", "title": "Structure of a test plan",
             "steps": [
                 ("Identify tests", "What will be tested."),
                 ("Purpose", "Why each test matters."),
                 ("Test data", "The data to use."),
                 ("Expected result", "What should happen."),
                 ("Actual result", "What really happened."),
             ],
             "caption": "Automation: macros, scripts and functional testing tools can rerun tests after every change."},
        ],
        "quiz": [
            ("What does regression testing check?", "That changes have not broken existing functionality."),
            ("A field accepts 1 to 8. Give an erroneous test value.", "Any non-number, e.g. 'four'."),
            ("What is the difference between unit and integration testing?", "Unit tests one component; integration tests components working together."),
            ("Why test components before integration?", "Faults are easier to find and fix in isolation."),
        ],
        "activity": {
            "title": "Test a login form",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "The form needs a username of 3 to 15 characters and a password of at least 8.",
                "Write a test plan with at least ten tests.",
                "Use all four types of test data.",
                "Run the tests on your teacher's sample code and record the results.",
            ],
            "success": [
                "All five columns completed",
                "Boundaries 3, 15 and 8 tested",
                "Failures clearly recorded",
            ],
        },
        "exit": [
            "What is closed box testing?",
            "Why write the expected result before testing?",
            "Which test would find a slow website on launch day?",
        ],
    },
    {
        "area": "core",
        "file": "core/09-emerging-issues-and-technologies.pptx",
        "title": "Emerging Issues and Technologies",
        "unit": "Core Paper 1",
        "spec": "3.1, 3.2",
        "pages": [CP1],
        "objectives": [
            "Explain how digital technology affects organisational culture and society.",
            "Describe digital inclusion, including bias in datasets.",
            "Evaluate the impact of emerging technologies.",
        ],
        "starter": "Generative AI can now write code. Will software developers still be needed in ten years? Why?",
        "slides": [
            {"type": "compare", "title": "Impact of digital technologies",
             "left": ("On organisational culture", [
                 "New ways of communicating",
                 "Higher expectations of productivity and availability",
                 "More staff monitoring",
                 "Remote, hybrid and in-office working",
                 "Automation, including AI",
             ]),
             "right": ("On society", [
                 "Job losses and changing skills",
                 "Less human decision-making",
                 "Privacy, digital footprint and surveillance",
                 "Isolation for some, better access for others",
                 "Generative AI and globalisation",
             ])},
            {"type": "bullets", "title": "Digital inclusion",
             "bullets": [
                 "Fair access needs suitable technology and connectivity.",
                 "Check datasets for bias before training or using them.",
                 "Follow best-practice codes and public sector accessibility regulations.",
                 "Consider users' age, digital and literacy skills, culture and accessibility needs.",
             ],
             "callout": "Biased training data produces biased software. Developers are responsible for checking it."},
            {"type": "cards", "title": "Emerging technologies",
             "cards": [
                 ("Processing and storage", "Quantum computing and growing storage demand."),
                 ("IoT", "Edge computing in industry, smart cities and homes."),
                 ("AI", "Generative AI and machine learning."),
                 ("Extended reality", "Augmented and virtual reality."),
                 ("Open source and blockchain", "Shared code and tamper-resistant ledgers."),
                 ("Autonomous machines", "Self-driving cars, robotic assembly. Plus environmental costs: rare metals, energy, disposal."),
             ]},
        ],
        "quiz": [
            ("Give two impacts of digital technology on society.", "Any two, e.g. job losses, privacy concerns, better access to information."),
            ("Why should developers check datasets for bias?", "Biased data leads to unfair or inaccurate software."),
            ("What is edge computing?", "Processing data near where it is collected rather than centrally."),
            ("Give one environmental impact of new technology.", "Rare metal use, energy use or disposal."),
        ],
        "activity": {
            "title": "Ethics review",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Your group is building an AI tool to shortlist job applicants.",
                "Identify three ways it could exclude or disadvantage people.",
                "Suggest a fix for each.",
                "Present your review in two minutes.",
            ],
            "success": [
                "Considers bias in training data",
                "Considers accessibility",
                "Fixes are realistic",
            ],
        },
        "exit": [
            "Which emerging technology will most change software development?",
            "Name one characteristic that affects inclusivity.",
            "Why does professional development matter for developers?",
        ],
    },
    {
        "area": "core",
        "file": "core/10-legislation-and-guidelines.pptx",
        "title": "Legislation and Guidelines",
        "unit": "Core Paper 1",
        "spec": "4.1, 4.2",
        "pages": [CP1],
        "objectives": [
            "Describe health and safety law for digital work.",
            "Explain data protection, computer misuse, equality and intellectual property law.",
            "Explain how codes of conduct and industry standards shape professional behaviour.",
            "Describe acceptable use policies and whistleblowing.",
        ],
        "starter": "You find that your company's app is collecting users' locations without telling them. What should you do?",
        "slides": [
            {"type": "compare", "title": "Health and safety for digital work",
             "left": ("Health and Safety at Work Act", [
                 "A safe working environment",
                 "Properly trained staff",
                 "Adequate welfare",
                 "Information, instruction and supervision",
             ]),
             "right": ("Display screen equipment", [
                 "Workstation assessments",
                 "Regular breaks from the screen",
                 "Eye tests on request",
                 "Training and information",
             ])},
            {"type": "cards", "title": "Key legislation",
             "cards": [
                 ("Data Protection Act / UK GDPR", "Protects personal data. Learn its eight principles."),
                 ("Computer Misuse Act 1990", "Unauthorised access, access with intent to commit further crimes, and unauthorised acts that impair a computer."),
                 ("Equality", "Nine protected characteristics; direct and indirect discrimination, harassment, victimisation."),
                 ("Intellectual property", "Unregistered designs, registered designs and patents."),
                 ("International law", "Some offences cross borders, e.g. in cyberspace and surveillance."),
             ]},
            {"type": "compare", "title": "Guidelines",
             "left": ("Codes of conduct", [
                 "Organisational, professional (BCS, IAP, CIISec) and governmental",
                 "Follow policy and law; minimise risk to the public",
                 "Competence, integrity and meeting deadlines",
                 "Confidentiality and trust",
             ]),
             "right": ("Standards and policies", [
                 "Standards: ISO, WCAG, W3C, IETF, BS, IEEE, PCI SSC",
                 "Acceptable use policy: permitted activities, etiquette, sanctions",
                 "Whistleblowing: a safe way to report wrongdoing",
             ])},
        ],
        "quiz": [
            ("Name two employer duties under the Health and Safety at Work Act.", "Any two of: safe environment, training, welfare, information, instruction, supervision."),
            ("Which law covers hacking into a system?", "The Computer Misuse Act 1990."),
            ("How many protected characteristics are there?", "Nine."),
            ("Which standard covers web accessibility?", "WCAG."),
        ],
        "activity": {
            "title": "Compliance check",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Review a feature list for a new fitness app from your teacher.",
                "Flag every feature that raises a legal or ethical issue.",
                "Name the law or guideline involved.",
                "Suggest a compliant alternative.",
            ],
            "success": [
                "Data protection issues identified",
                "Accessibility considered",
                "Alternatives are practical",
            ],
        },
        "exit": [
            "Why must developers know data protection law?",
            "What is an acceptable use policy for?",
            "Why is whistleblowing protected?",
        ],
    },
]
