"""Core Paper 2 decks (business, data, digital environments, security) and the ESP deck."""

CP2 = "01-core-component/02-core-paper-2.md"
ESP = "01-core-component/03-employer-set-project.md"

DECKS = [
    {
        "area": "core",
        "file": "core/11-the-business-context.pptx",
        "title": "The Business Context",
        "unit": "Core Paper 2",
        "spec": "5.1, 5.2, 5.3",
        "pages": [CP2],
        "objectives": [
            "Describe business sectors, models and stakeholders.",
            "Explain how digital systems add value to each part of a business.",
            "Describe the user needs and quality expectations software must meet.",
            "Explain the risks and impacts of using digital systems.",
        ],
        "starter": "Name an app you use every day. Who makes money from it, and how?",
        "slides": [
            {"type": "cards", "title": "The business environment",
             "cards": [
                 ("Sectors", "Private (SME, large enterprise, NGO), public, and voluntary or charity."),
                 ("Business models", "B2C sells to consumers, B2B to businesses, B2M to a mass market."),
                 ("Internal stakeholders", "Owners, directors and employees."),
                 ("External stakeholders", "Customers, suppliers, shareholders, outsourced services, investors, government."),
             ]},
            {"type": "table", "title": "Digital value across the business",
             "header": ["Area", "How digital systems help"],
             "widths": [2.4, 6],
             "rows": [
                 ["Sales and marketing", "Market research, social media, online selling, personalisation, analytics"],
                 ["Research and development", "Unique products and services"],
                 ["HR", "Staff records, performance and training"],
                 ["Operations", "Communication, automation, remote working, document sharing"],
                 ["Management", "Real-time KPI monitoring"],
                 ["Logistics and finance", "Automated stock control; lower costs, more revenue, better reporting"],
             ]},
            {"type": "cards", "title": "What users expect from software",
             "cards": [
                 ("Functionality", "Does the job well."),
                 ("Fewer pain points", "Fast response, simple tasks."),
                 ("Accessibility", "Usable by everyone."),
                 ("Compatibility", "Works with legacy, future and external systems."),
                 ("Availability", "Minimal downtime."),
                 ("Support", "Good end-user support and easy installation."),
             ]},
            {"type": "compare", "title": "Risks and impacts",
             "left": ("Risks", [
                 "Security and privacy breaches",
                 "Legal or regulatory non-compliance",
                 "Excluding users through bias or poor UX",
                 "Rival technologies",
                 "Over-reliance, failure or systems unfit for purpose",
             ]),
             "right": ("Impacts", [
                 "Legal action",
                 "Fines",
                 "Reputational damage",
                 "Loss of licence to practise",
                 "Lost business",
             ])},
        ],
        "quiz": [
            ("What does B2C mean?", "Business to consumer."),
            ("Is a shareholder an internal or external stakeholder?", "External."),
            ("What is a 'pain point'?", "Something that frustrates users, such as slow response or complex tasks."),
            ("Name two impacts of a data breach.", "Any two of: legal action, fines, reputational damage, loss of licence, lost business."),
        ],
        "activity": {
            "title": "Pitch a feature",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Choose a local business and a software feature that would help it.",
                "Identify which business area gains value and how.",
                "List the stakeholders affected.",
                "Identify two risks and how you would reduce them.",
            ],
            "success": [
                "Value is specific and measurable",
                "Stakeholders split internal and external",
                "Risks are realistic",
            ],
        },
        "exit": [
            "Give an example of a B2B software product.",
            "Which user expectation matters most for a banking app?",
            "How can poor UX exclude users?",
        ],
    },
    {
        "area": "core",
        "file": "core/12-technical-change-management.pptx",
        "title": "Technical Change Management",
        "unit": "Core Paper 2",
        "spec": "5.4",
        "pages": [CP2],
        "objectives": [
            "Identify internal and external triggers for change.",
            "Explain the change management process and the role of the CAB.",
            "Compare implementation methods and plan for rollback.",
            "Assess the feasibility of a digital project.",
        ],
        "starter": "Your school switches to a new online homework system overnight. What could go wrong?",
        "slides": [
            {"type": "compare", "title": "Triggers for change",
             "left": ("Internal", [
                 "Restructuring, expansion or downsizing",
                 "New strategic objectives",
                 "Crises and system failures",
             ]),
             "right": ("External (PESTLE)", [
                 "Political and legal: new laws",
                 "Economic: recession, competitors",
                 "Social: remote working, trends",
                 "Technological: new tech, zero-days",
                 "Environmental: sustainability",
             ])},
            {"type": "process", "title": "The change management process",
             "steps": [
                 ("Identify", "New system or amendment? CAB reviews and approves."),
                 ("Plan", "SMARTER objectives, impact, resources."),
                 ("Communicate", "Share risks and impact with stakeholders."),
                 ("Build and test", "Configure and fully test the new system."),
                 ("Implement", "Parallel, phased, direct or pilot."),
                 ("Review", "Document, train, monitor, version control."),
             ],
             "notes": "SMARTER: specific, measurable, achievable, realistic, time-bound, evaluated, reviewed. Rollback needs a backup method, a backup location and a recovery plan."},
            {"type": "table", "title": "Implementation methods",
             "header": ["Method", "How it works", "Trade-off"],
             "widths": [1.5, 3.8, 3.5],
             "rows": [
                 ["Direct", "Switch old off and new on", "Fast and cheap, high risk"],
                 ["Parallel", "Run both side by side", "Safe fallback, double the work"],
                 ["Phased", "One part at a time", "Lower risk, slower"],
                 ["Pilot", "One team or site first", "Problems found early, slow rollout"],
             ]},
            {"type": "cards", "title": "Feasibility",
             "cards": [
                 ("Benefits and drawbacks", "Savings against cost; impact on processes and reputation."),
                 ("Risks", "Resistance, misuse, inadequate support or knowledge, disruption."),
                 ("Constraints", "Budget, time and resources."),
             ]},
        ],
        "quiz": [
            ("What does the CAB do?", "Prioritises, reviews and approves change requests and monitors progress."),
            ("Which implementation method is riskiest?", "Direct."),
            ("Why plan a rollback?", "To restore the old system if the change fails."),
            ("How does version control software help change management?", "It tracks every change and lets you return to earlier versions."),
        ],
        "activity": {
            "title": "Plan a release",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "A college is replacing its paper attendance registers with an app.",
                "Write three SMARTER objectives.",
                "Choose an implementation method and justify it.",
                "Write a rollback and training plan.",
            ],
            "success": [
                "Objectives are measurable",
                "Method suits the risk",
                "Rollback names what is backed up and where",
            ],
        },
        "exit": [
            "Give one external trigger for change.",
            "When would a pilot be the best method?",
            "What goes in a post-implementation review?",
        ],
    },
    {
        "area": "core",
        "file": "core/13-data-fundamentals.pptx",
        "title": "Data Fundamentals",
        "unit": "Core Paper 2",
        "spec": "6.1 to 6.6",
        "pages": [CP2],
        "objectives": [
            "Distinguish between data, information and knowledge.",
            "Describe sources of data and how organisations use it.",
            "Classify data and choose suitable data types and formats.",
            "Describe structures for storing data.",
        ],
        "starter": "'15, 22, 9'. Is that data or information? What would make it useful?",
        "slides": [
            {"type": "process", "title": "Data, information and knowledge",
             "steps": [
                 ("Data", "Raw facts with no context: 15, 22, 9"),
                 ("Information", "Data with context: minutes each user spent in the app today"),
                 ("Knowledge", "Understanding applied: users drop off after 10 minutes, so simplify the menu"),
             ]},
            {"type": "cards", "title": "Sources and uses of data",
             "cards": [
                 ("Sources", "Humans (forms), AI (beware feedback loops), sensors, IoT devices, transactions."),
                 ("Value", "Judged on quantity, timeframe, source and veracity, used ethically."),
                 ("Uses", "Pattern analysis, system performance, user monitoring, targeted marketing, threat assessment."),
                 ("Transforming data", "Manipulating, analysing and processing."),
             ]},
            {"type": "compare", "title": "Data taxonomy",
             "left": ("Quantitative (structured)", [
                 "Discrete: whole counts",
                 "Continuous: measured values",
                 "Categorical: fixed groups",
             ]),
             "right": ("Qualitative (unstructured)", [
                 "Text, images, audio, video",
                 "Stored and retrieved as a single object",
                 "Or codified into structured data",
             ])},
            {"type": "table", "title": "Data types and formats",
             "header": ["Data types", "Data formats"],
             "widths": [4.3, 4.3],
             "rows": [
                 ["Integer, real: numbers", "CSV: comma-separated values"],
                 ["Character, string: text", "JSON: key and value pairs for web APIs"],
                 ["Boolean: true or false", "XML: data in named tags"],
                 ["Date: calendar dates and times", "Text file: plain text"],
                 ["Blob: binary objects such as images", "ASCII and UTF-8: character encodings"],
             ]},
            {"type": "cards", "title": "Structures for storing data",
             "cards": [
                 ("Metadata", "Data about data that gives it context."),
                 ("File based", "Data in individual files."),
                 ("Directory based", "Files organised into folders."),
                 ("Hierarchy based", "Parent and child levels, like a tree."),
             ]},
        ],
        "quiz": [
            ("What turns data into information?", "Context and meaning."),
            ("Is 'number of downloads' discrete or continuous?", "Discrete."),
            ("Which format is common for web APIs?", "JSON."),
            ("What does UTF-8 support that ASCII does not?", "Characters from every language (Unicode)."),
            ("What is metadata?", "Data describing other data."),
        ],
        "activity": {
            "title": "CSV to JSON",
            "time": "25 minutes",
            "format": "Pairs, in Python",
            "steps": [
                "Create a CSV of five products: name, price, in stock.",
                "Read it in Python and convert each row to the right data types.",
                "Output the same data as JSON using the json module.",
                "Explain which format suits which purpose.",
            ],
            "success": [
                "Types converted correctly",
                "Valid JSON output",
                "Clear justification",
            ],
        },
        "exit": [
            "Give an example of knowledge from app data.",
            "Why is AI-generated data risky?",
            "When would you choose XML over JSON?",
        ],
    },
    {
        "area": "core",
        "file": "core/14-data-quality-systems-and-analysis.pptx",
        "title": "Data Quality, Systems and Analysis",
        "unit": "Core Paper 2",
        "spec": "6.7 to 6.12",
        "pages": [CP2],
        "objectives": [
            "Explain the six Vs of Big Data and data quality assurance.",
            "Describe data wrangling and how to reduce data entry errors.",
            "Choose data visualisations and data models.",
            "Compare data access mechanisms and analysis tools.",
        ],
        "starter": "A sign-up form lets people type their country. How many ways could someone type 'United Kingdom'?",
        "slides": [
            {"type": "cards", "title": "The six Vs of Big Data",
             "cards": [
                 ("Volume", "The amount of data."),
                 ("Variety", "Many types of data."),
                 ("Variability", "Meaning and flow change."),
                 ("Velocity", "Speed of arrival."),
                 ("Veracity", "Accuracy and trust."),
                 ("Value", "Useful insight."),
             ],
             "notes": "Quality assurance: validation, verification, reliability, consistency, integrity, redundancy. Maintenance depends on time, skills and cost."},
            {"type": "process", "title": "Data wrangling",
             "steps": [
                 ("Structure", "Shape raw data."),
                 ("Clean", "Remove errors and duplicates."),
                 ("Validate", "Check it meets rules."),
                 ("Enrich", "Add useful data."),
                 ("Output", "Deliver it for use."),
             ],
             "caption": "Reduce transcription and transposition errors with validation, double entry, drop-downs and pre-filled boxes."},
            {"type": "cards", "title": "Visualisation and data models",
             "cards": [
                 ("Visualisation", "Graphs, charts, tables, reports, dashboards, infographics. Choose by data type, audience and brief."),
                 ("Hierarchical model", "Parent and child tree."),
                 ("Network model", "Records with many links."),
                 ("Relational model", "Tables of rows and columns linked by keys."),
             ]},
            {"type": "compare", "title": "Access and analysis",
             "left": ("Access across platforms", [
                 "Permissions: authorisation, privileges, rights, rules",
                 "RBAC: by role",
                 "RuBAC: by rules",
                 "APIs: controlled access for other software",
             ]),
             "right": ("Analysis tools", [
                 "Data warehouse, data lake, data mart",
                 "Data mining and reporting",
                 "Business intelligence for finance and CRM",
             ])},
        ],
        "quiz": [
            ("Which V refers to trustworthiness?", "Veracity."),
            ("What is a transposition error?", "Swapping characters, e.g. 1234 becomes 1243."),
            ("Which data model uses linked tables?", "Relational."),
            ("What does a data lake hold?", "Raw data in any format."),
        ],
        "activity": {
            "title": "Clean and chart",
            "time": "30 minutes",
            "format": "Individual, in Python",
            "steps": [
                "Load the messy CSV from your teacher with pandas.",
                "Clean it: fix inconsistent values and remove duplicates.",
                "Calculate a total and an average.",
                "Plot a labelled chart with Matplotlib for a manager.",
            ],
            "success": [
                "Duplicates removed",
                "Calculations correct",
                "Chart has title, labels and legend",
            ],
            "notes": "This mirrors the pandas and Matplotlib skills needed in the Employer Set Project.",
        },
        "exit": [
            "Why use a drop-down instead of free text?",
            "Which visualisation suits a trend over time?",
            "When is an API the right access mechanism?",
        ],
    },
    {
        "area": "core",
        "file": "core/15-hardware-and-software.pptx",
        "title": "Hardware and Software",
        "unit": "Core Paper 2",
        "spec": "7.1, 7.2",
        "pages": [CP2],
        "objectives": [
            "Identify computer types and hardware components.",
            "Describe operating system types and utilities.",
            "Explain IDEs, compilers and interpreters.",
        ],
        "starter": "Why does a game run faster on a gaming PC than on a school laptop? List every reason you can.",
        "slides": [
            {"type": "table", "title": "Hardware",
             "header": ["Component", "Key points"],
             "widths": [2.2, 6.4],
             "rows": [
                 ["Computer types", "Personal computers, mobile devices, servers, embedded devices"],
                 ["Processor", "Cores, clock speed and cache; mobile processors save power"],
                 ["Memory", "RAM is volatile working memory; ROM holds start-up instructions"],
                 ["Storage", "Magnetic, solid state, optical"],
                 ["Other", "Motherboard, GPU, network interfaces (PCI, USB), cooling, sensors"],
             ]},
            {"type": "table", "title": "Operating system types",
             "header": ["Type", "Features"],
             "widths": [1.8, 6.8],
             "rows": [
                 ["Batch", "Non-interactive, high volume, scheduled jobs"],
                 ["Multitasking", "Runs tasks concurrently using time-slicing and interrupts"],
                 ["Real-time", "Responds instantly, for control and transactions"],
                 ["Network", "Shares resources and manages users"],
                 ["Mobile", "Low processing needs, long battery life"],
             ],
             "caption": "Utilities: file management, defragmenters, compression, package managers, protection and backup software."},
            {"type": "compare", "title": "Code development tools",
             "left": ("IDE", [
                 "Editor with syntax highlighting",
                 "Debugging tools such as breakpoints",
                 "Screen design tools",
                 "Everything in one place",
             ]),
             "right": ("Translators", [
                 "Compiler: translates the whole program before it runs; fast to run",
                 "Interpreter: translates and runs line by line; easier to debug",
                 "Python is usually interpreted",
             ])},
        ],
        "quiz": [
            ("Which memory is volatile?", "RAM."),
            ("Which OS type would control a pacemaker?", "Real-time."),
            ("What is the difference between a compiler and an interpreter?", "A compiler translates the whole program first; an interpreter translates and runs line by line."),
            ("Name two features of an IDE.", "Any two of: editor, debugger, screen design, syntax highlighting."),
        ],
        "activity": {
            "title": "Choose a development setup",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Three projects: a mobile game, a data analysis script, and a system for a factory robot.",
                "Choose hardware, an OS type and a language approach for each.",
                "Choose development tools.",
                "Justify each choice.",
            ],
            "success": [
                "OS type matches the use",
                "Compiled or interpreted choice justified",
                "Hardware realistic",
            ],
        },
        "exit": [
            "Why might a developer prefer an interpreter while testing?",
            "What does a package manager do?",
            "Name one embedded device you used today.",
        ],
    },
    {
        "area": "core",
        "file": "core/16-networks.pptx",
        "title": "Networks",
        "unit": "Core Paper 2",
        "spec": "7.3",
        "pages": [CP2],
        "objectives": [
            "Compare network types, topologies and models.",
            "Describe the OSI and TCP/IP models.",
            "Explain data packets, packet switching and error handling.",
            "Match protocols to their purpose.",
        ],
        "starter": "When your app calls an API, what do you think happens between your device and the server?",
        "slides": [
            {"type": "cards", "title": "Network types and topologies",
             "cards": [
                 ("PAN, LAN, MAN, WAN", "Personal, local, metropolitan and wide area networks."),
                 ("VPN", "A private, encrypted connection across a public network."),
                 ("Topologies", "Star, mesh and tree; logical versus physical."),
                 ("Models", "Client-server, thin client, peer-to-peer."),
             ]},
            {"type": "table", "title": "The OSI and TCP/IP models",
             "header": ["OSI layer", "Job", "TCP/IP layer"],
             "widths": [2, 4.5, 2],
             "rows": [
                 ["7 Application", "Services for applications", "Application"],
                 ["6 Presentation", "Formatting, encryption", "Application"],
                 ["5 Session", "Manages sessions", "Application"],
                 ["4 Transport", "Reliable delivery, ports", "Transport"],
                 ["3 Network", "Addressing and routing", "Internet"],
                 ["2 Data link", "Frames, MAC addresses", "Network"],
                 ["1 Physical", "Cables and signals", "Network"],
             ]},
            {"type": "bullets", "title": "Data packets",
             "bullets": [
                 "Header: source and destination addresses, packet number, protocol.",
                 "Payload: the data itself.",
                 "Trailer: error checking, e.g. a cyclic redundancy check (CRC).",
                 "Packet switching: packets take different routes and are reassembled.",
             ],
             "callout": "Bandwidth is how much data can flow; latency is the delay. Both affect how fast your app feels."},
            {"type": "table", "title": "Common protocols",
             "header": ["Group", "Protocols", "Purpose"],
             "widths": [1.6, 2.6, 4.4],
             "rows": [
                 ["Web", "HTTP, HTTPS", "Web pages and APIs; HTTPS is encrypted"],
                 ["Mail", "SMTP, POP, IMAP", "Send, download or sync mail"],
                 ["Routing", "RIP, OSPF", "Routers share routes"],
                 ["Application", "FTP, SFTP, DHCP, DNS", "File transfer, IP addresses, name lookup"],
             ]},
        ],
        "quiz": [
            ("Which layer handles routing in the OSI model?", "Layer 3, network."),
            ("What is a CRC for?", "Detecting errors in transmitted data."),
            ("Which protocol turns a domain name into an IP address?", "DNS."),
            ("What is latency?", "The delay before data arrives."),
        ],
        "activity": {
            "title": "Trace an API call",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Draw what happens when an app requests weather data from an API.",
                "Label the protocols used (DNS, HTTPS, TCP/IP).",
                "Show which OSI layers are involved.",
                "Suggest what the app should do if packets are lost.",
            ],
            "success": [
                "DNS lookup included",
                "Layers in the right order",
                "Sensible error handling",
            ],
        },
        "exit": [
            "Why use HTTPS for an API?",
            "What is packet switching?",
            "Give one benefit of client-server networks.",
        ],
    },
    {
        "area": "core",
        "file": "core/17-virtual-cloud-and-resilient-environments.pptx",
        "title": "Virtual, Cloud and Resilient Environments",
        "unit": "Core Paper 2",
        "spec": "7.4, 7.5, 7.6",
        "pages": [CP2],
        "objectives": [
            "Describe virtual machines, hypervisors and virtualisation trade-offs.",
            "Compare IaaS, PaaS and SaaS.",
            "Explain methods to make digital environments resilient.",
        ],
        "starter": "Where does your code actually run when you deploy an app 'to the cloud'?",
        "slides": [
            {"type": "compare", "title": "Virtual environments",
             "left": ("Components and features", [
                 "Virtual machines: PCs, switches, routers, servers",
                 "Type 1 hypervisor on the hardware; Type 2 on an OS",
                 "Isolation, emulation, portability, sharing",
             ]),
             "right": ("Benefits and drawbacks", [
                 "Cost-effective at scale, easy to manage",
                 "Better disaster recovery and testing",
                 "But: extra hardware load and slower execution",
                 "But: performance can be misrepresented",
             ])},
            {"type": "table", "title": "Cloud delivery models",
             "header": ["Model", "Client manages", "Provider manages"],
             "widths": [1.2, 3.7, 3.7],
             "rows": [
                 ["IaaS", "Apps, OS, runtime, data, accounts", "Virtualisation and hardware"],
                 ["PaaS", "Apps, data, accounts", "Hardware, virtualisation, OS, runtime"],
                 ["SaaS", "Accounts and data", "Everything else"],
             ],
             "caption": "Cloud can be private or public. Benefits: portability, elasticity, fewer storage limits, cost."},
            {"type": "cards", "title": "Making environments resilient",
             "cards": [
                 ("Updates and patches", "Fix vulnerabilities quickly."),
                 ("Hardware replacement", "Rolling plans and secure disposal."),
                 ("Redundancy", "Duplicate data and systems."),
                 ("Device hardening", "Remove unneeded ports, apps and access."),
                 ("Backups and sites", "Onsite, offsite, cloud; hot, warm and cold sites."),
                 ("Procedures", "Training, induction and careful rollout."),
             ]},
        ],
        "quiz": [
            ("Which hypervisor type runs directly on hardware?", "Type 1."),
            ("In PaaS, who manages the operating system?", "The provider."),
            ("Give one drawback of virtualisation.", "Extra hardware load or slower execution."),
            ("What is a hot site?", "A fully equipped backup site ready to take over almost immediately."),
        ],
        "activity": {
            "title": "Deploy decision",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "You are deploying a web app for a small charity.",
                "Choose IaaS, PaaS or SaaS and justify it.",
                "List what the charity still has to manage.",
                "Add three resilience measures.",
            ],
            "success": [
                "Model matches the charity's skills",
                "Responsibilities correct",
                "Resilience measures realistic",
            ],
        },
        "exit": [
            "Why do developers like virtual machines for testing?",
            "Which cloud model gives the most control?",
            "Why store backups offsite?",
        ],
    },
    {
        "area": "core",
        "file": "core/18-security-threats-and-vulnerabilities.pptx",
        "title": "Security Threats and Vulnerabilities",
        "unit": "Core Paper 2",
        "spec": "8.1, 8.2",
        "pages": [CP2],
        "objectives": [
            "Explain why confidential information must be protected.",
            "Describe technical threats, including SQL injection and insecure APIs.",
            "Describe human and physical threats and vulnerabilities.",
            "Suggest prevention and mitigation for each.",
        ],
        "starter": "A login form sends whatever the user types straight into a database query. What could an attacker type?",
        "slides": [
            {"type": "compare", "title": "Why confidentiality matters",
             "left": ("What organisations hold", [
                 "HR data: salaries, personal details",
                 "Commercial data: clients, IP, sales, contracts",
                 "Access data: passwords, MFA, PINs, biometrics",
             ]),
             "right": ("If it leaks", [
                 "Non-compliance and loss of licence",
                 "Lost trust and reputational damage",
                 "Fines, refunds, lost earnings",
                 "Legal action and reduced security",
             ])},
            {"type": "cards", "title": "Technical threats",
             "cards": [
                 ("Botnets and DoS / DDoS", "Floods of traffic that take services down."),
                 ("Hacking techniques", "Brute force, cross-site scripting, SQL injection, buffer overflow."),
                 ("Malware", "Viruses, worms, keyloggers, ransomware, spyware, remote access trojans."),
                 ("Social engineering", "Phishing, spear phishing, smishing, vishing, pharming, watering holes, USB baiting."),
                 ("Insecure APIs", "APIs without proper authentication or input checks."),
                 ("Interception", "DNS attacks, man-in-the-middle attacks, open Wi-Fi."),
             ]},
            {"type": "table", "title": "Developer defences",
             "header": ["Threat", "Prevention in code"],
             "widths": [2.6, 6],
             "rows": [
                 ["SQL injection", "Parameterised queries; never build SQL from raw input"],
                 ["Cross-site scripting", "Escape output and validate input"],
                 ["Buffer overflow", "Check lengths and use safe functions"],
                 ["Insecure APIs", "Authentication, API keys, rate limits, input validation"],
                 ["Brute force", "Account lockout, MFA, strong password rules"],
             ]},
            {"type": "compare", "title": "Human and physical risks",
             "left": ("Human threats", [
                 "Human error: confirmation boxes, training",
                 "Malicious employees: remove access fast",
                 "Disguised criminals: ID checks, escorts",
                 "Poor cyber hygiene: lock screens, password managers",
             ]),
             "right": ("Vulnerabilities", [
                 "Weak encryption, poor password policy, no MFA",
                 "Out-of-date software and firmware, zero-days",
                 "Poor physical access control, shoulder surfing",
                 "Natural disasters",
             ])},
        ],
        "quiz": [
            ("How do you prevent SQL injection?", "Use parameterised queries instead of building SQL from user input."),
            ("What is spear phishing?", "A phishing attack targeted at a specific person or organisation."),
            ("What makes an API insecure?", "Weak or no authentication or input validation."),
            ("What is a zero-day?", "A flaw exploited before a patch exists."),
        ],
        "activity": {
            "title": "Secure the login",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Review the vulnerable login code from your teacher.",
                "Identify every security weakness.",
                "Rewrite it using parameterised queries, hashing and lockout.",
                "Explain each fix in one sentence.",
            ],
            "success": [
                "SQL injection fixed",
                "Passwords never stored in plain text",
                "Lockout after repeated failures",
            ],
            "notes": "Use a small SQLite example so students can see the injection working before fixing it.",
        },
        "exit": [
            "Which threat can a developer prevent most directly?",
            "Why is open Wi-Fi risky?",
            "What is a man-in-the-middle attack?",
        ],
    },
    {
        "area": "core",
        "file": "core/19-threat-mitigation-cia-and-iaaa.pptx",
        "title": "Threat Mitigation, the CIA Triad and IAAA",
        "unit": "Core Paper 2",
        "spec": "8.3, 8.4",
        "pages": [CP2],
        "objectives": [
            "Describe threat mitigation techniques.",
            "Explain firewall configuration and network segregation.",
            "Explain how the CIA triad properties support each other.",
            "Describe the IAAA model.",
        ],
        "starter": "Why do most websites ask you to verify your email address before you can use your account?",
        "slides": [
            {"type": "cards", "title": "Mitigation techniques",
             "cards": [
                 ("Protect devices", "Security settings, anti-malware, hardening, updates."),
                 ("Control access", "Access policies, MFA, password managers."),
                 ("Protect data", "Hashing, symmetric and asymmetric encryption; backups."),
                 ("Protect networks", "Intrusion detection, VPNs, air gaps, API certification."),
                 ("People", "Vetting and training."),
                 ("Test", "Port scanning and ethical penetration testing."),
             ]},
            {"type": "compare", "title": "Internet security processes",
             "left": ("Firewall configuration", [
                 "Inbound and outbound rules",
                 "Traffic type rules",
                 "Application rules",
                 "IP address rules",
             ]),
             "right": ("Network protection", [
                 "Segregation: virtual, physical, offline",
                 "Network monitoring",
                 "Port scanning",
             ])},
            {"type": "cards", "title": "The CIA triad",
             "cards": [
                 ("Confidentiality", "Controlling who can access data."),
                 ("Integrity", "Data is not tampered with. Supported by confidentiality."),
                 ("Availability", "Data is there when needed. Supported by integrity."),
             ]},
            {"type": "process", "title": "The IAAA model",
             "steps": [
                 ("Identification", "Who are you? Username, card or biometric."),
                 ("Authentication", "Prove it: password, MFA, biometrics."),
                 ("Authorisation", "What can you do? Roles and access control lists."),
                 ("Accountability", "What did you do? Audit logs."),
             ]},
        ],
        "quiz": [
            ("Why hash passwords rather than encrypt them?", "Hashing is one way, so stored passwords cannot be reversed."),
            ("What is an air gap?", "Physically isolating a system from other networks."),
            ("Which IAAA stage checks permissions?", "Authorisation."),
            ("Which CIA property does a DDoS attack target?", "Availability."),
        ],
        "activity": {
            "title": "Design secure accounts",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Design the account system for a school revision app.",
                "Map each IAAA stage to a feature.",
                "Link each feature to C, I or A.",
                "Choose two mitigation techniques for the server.",
            ],
            "success": [
                "All four IAAA stages covered",
                "Passwords hashed",
                "Audit logging included",
            ],
        },
        "exit": [
            "Give an example of multi-factor authentication.",
            "What does an audit log provide?",
            "Why is ethical hacking legal?",
        ],
    },
    {
        "area": "core",
        "file": "core/20-employer-set-project.pptx",
        "title": "The Employer Set Project",
        "unit": "Core Component",
        "spec": "Employer Set Project",
        "pages": [ESP],
        "objectives": [
            "Explain the weighting and conditions of the Employer Set Project.",
            "Describe what each task requires.",
            "Plan how to prepare for each task.",
        ],
        "starter": "In the ESP you cannot use the internet or AI tools. Which skills do you need to have practised beforehand?",
        "slides": [
            {"type": "bullets", "title": "What is the ESP?",
             "bullets": [
                 "40% of the core assessments, 100 marks.",
                 "Up to 14 hours 30 minutes across several sessions.",
                 "A realistic vocational brief, externally set and marked.",
                 "No internet access or AI tools during assessed sessions.",
             ],
             "callout": "The order and detail of tasks can change each series, but the number and focus of tasks stay the same."},
            {"type": "process", "title": "The tasks",
             "steps": [
                 ("Pre-task", "Research the industry context. Not assessed."),
                 ("Task 1", "Gantt chart, resource and cost plan, rationale."),
                 ("Task 2", "Test and fix defects in existing code."),
                 ("Task 3", "Decompose and design a solution."),
                 ("Task 4a", "Develop the solution in Python."),
                 ("Task 4b", "Reflective evaluation."),
             ]},
            {"type": "cards", "title": "What earns marks",
             "cards": [
                 ("Task 2 testing", "Tests, purpose, valid, valid extreme, invalid, invalid extreme and erroneous data, expected and actual results."),
                 ("Task 3 design", "Good decomposition, clear algorithms, correct conventions, a design a third party could build."),
                 ("Task 4a code", "Functions, meaningful names, comments, local variables, constants, exception handling."),
                 ("User experience", "Simple input, meaningful messages, data visualisation with Matplotlib."),
             ]},
            {"type": "bullets", "title": "How to prepare",
             "bullets": [
                 "Practise Gantt charts and cost plans against a deadline.",
                 "Practise finding and fixing bugs in code you did not write.",
                 "Get fluent with pandas and Matplotlib on CSV files.",
                 "Practise flowcharts with correct symbols.",
                 "Write reflections against success criteria.",
             ],
             "callout": "With no internet, you need the Python reference in your head. Practise without looking things up."},
        ],
        "quiz": [
            ("What percentage of the core assessments is the ESP?", "40%."),
            ("Name the five types of test data in Task 2.", "Valid, valid extreme, invalid, invalid extreme, erroneous."),
            ("Which library is suggested for graphs?", "Matplotlib."),
            ("What must a Task 3 design allow a third party to do?", "Build the proposed solution from it."),
        ],
        "activity": {
            "title": "Mini Task 2",
            "time": "40 minutes",
            "format": "Individual",
            "steps": [
                "Your teacher gives you a short program with four defects.",
                "Write a test table before changing anything.",
                "Fix each defect and retest.",
                "Justify each fix in one sentence.",
            ],
            "success": [
                "All five test data types used",
                "Every defect fixed",
                "Expected and actual results compared",
            ],
        },
        "exit": [
            "Which ESP task are you most worried about?",
            "What makes code well organised?",
            "What goes in a reflective evaluation?",
        ],
    },
]
