"""Occupational specialism decks (Digital Software Development)."""

SP = "02-occupational-specialism/"
ANALYSE = SP + "01-analyse-a-problem.md"
ETHICS = SP + "02-ethics-and-risk.md"
SOURCES = SP + "03-sources-of-knowledge.md"
DESIGN = SP + "04-design.md"
COLLAB = SP + "05-social-and-collaborative-environment.md"
IMPL = SP + "06-implementation.md"
TESTING = SP + "07-testing.md"
CHANGE = SP + "08-change-maintain-support.md"

DECKS = [
    {
        "area": "spec",
        "file": "specialism/01-sdlc-and-requirements.pptx",
        "title": "The Software Development Lifecycle and Requirements",
        "unit": "Specialism Content Area 1",
        "spec": "1.1, 1.4",
        "pages": [ANALYSE],
        "objectives": [
            "Describe each stage of the software development lifecycle.",
            "Explain what happens during planning and requirement analysis.",
            "Write functional and non-functional requirements.",
            "Explain secure by design and spike testing.",
        ],
        "starter": "A client says 'I want an app for my bakery.' What questions do you need to ask before writing any code?",
        "slides": [
            {"type": "process", "title": "The SDLC",
             "steps": [
                 ("Research", "Understand the brief, market and your own skills gaps."),
                 ("Plan", "Requirements, KPIs, schedule, costs, language, risks."),
                 ("User analysis", "User stories, activity diagrams, ERDs."),
                 ("Design", "Interfaces, algorithms, data; review any AI-generated code."),
                 ("Develop and test", "Prototype, module, integration, automated and user tests."),
                 ("Deploy", "Install, configure, document, version control."),
                 ("Maintain", "Support, bug fixes, training, updates."),
             ]},
            {"type": "cards", "title": "Planning and requirement analysis",
             "cards": [
                 ("Scope", "Turn the brief into a project proposal with business requirements."),
                 ("Computational thinking", "Decompose the problem, spot patterns, abstract the detail."),
                 ("Measures", "Set KPIs, performance constraints and user acceptance criteria."),
                 ("Resources", "Schedule tasks and milestones, allocate resources and estimate costs."),
                 ("Language choice", "Suitability, policy, scalability, security, staff, cost, reliability."),
                 ("Risk", "Identify risks and how to mitigate them."),
             ]},
            {"type": "compare", "title": "Functional and non-functional requirements",
             "left": ("Functional: what it does", [
                 "Inputs needed",
                 "Data needed",
                 "Processing that must happen",
                 "The system's logic",
                 "Platforms it runs on",
             ]),
             "right": ("Non-functional: how well", [
                 "Security",
                 "Accessibility",
                 "Scalability",
                 "KPIs for responsiveness, load and reliability",
                 "User acceptance criteria",
             ]),
             "notes": "Secure by design: security shapes both kinds of requirement from the start. Spike testing is early experimentation to work out the scope of a problem."},
            {"type": "cards", "title": "User analysis tools",
             "cards": [
                 ("User stories", "As a customer, I want to order ahead, so that I skip the queue."),
                 ("Activity and process diagrams", "Show the steps a user or system goes through."),
                 ("Mind maps and road maps", "Explore ideas and plan releases over time."),
                 ("Entity relationship diagrams", "Show the data and how it links."),
             ]},
        ],
        "quiz": [
            ("Name the SDLC stage where user stories are written.", "Performing a user analysis."),
            ("Is 'the app loads in under 2 seconds' functional or non-functional?", "Non-functional."),
            ("What is secure by design?", "Building security into decisions from the start."),
            ("What is spike testing used for?", "Early investigation to establish requirements and scope."),
            ("Why review AI-generated code?", "To make sure it actually meets the requirements."),
        ],
        "activity": {
            "title": "Requirements for the bakery app",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Write five user stories for the bakery app.",
                "Turn them into functional requirements.",
                "Add four non-functional requirements with measurable KPIs.",
                "Write acceptance criteria for one user story.",
            ],
            "success": [
                "Stories follow 'As a... I want... so that...'",
                "KPIs are measurable",
                "Security and accessibility included",
            ],
        },
        "exit": [
            "Which SDLC stage do you think is most often rushed?",
            "Give one non-functional requirement for a game.",
            "Why set KPIs before building?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/02-team-roles-and-project-methodologies.pptx",
        "title": "Team Roles and Project Methodologies",
        "unit": "Specialism Content Area 1",
        "spec": "1.2, 1.3",
        "pages": [ANALYSE],
        "objectives": [
            "Describe the roles in a digital team.",
            "Compare Agile, Scaled Agile, Waterfall, RAD, Lean and UCD.",
            "Select a methodology for a given project.",
        ],
        "starter": "Who decides what goes into an app: the developer, the designer or the client? Why?",
        "slides": [
            {"type": "table", "title": "Roles in the digital team",
             "header": ["Role", "Responsibility"],
             "widths": [2.6, 6],
             "rows": [
                 ["Product owner / client", "Sets and communicates the requirements"],
                 ["Scrum master", "Keeps the team cohesive and resourced"],
                 ["Technical lead / project manager", "Technical guidance / budget, scope, schedule, risk, quality"],
                 ["Systems analyst / UX-UI designer", "Analyses systems and writes requirements / researches users and designs the interface"],
                 ["Developer / operations / security engineer", "Builds the solution / keeps it stable / keeps it secure"],
                 ["Software tester", "Quality assurance across the product and process"],
             ]},
            {"type": "compare", "title": "Agile and Waterfall",
             "left": ("Agile", [
                 "Incremental: sprints, epics, stories, spikes",
                 "Requirements can keep changing",
                 "Users see working software every iteration",
                 "Less formal documentation",
                 "Scaled Agile extends it to large teams",
             ]),
             "right": ("Waterfall", [
                 "Rigid, systematic stages",
                 "Progress measured by completed artefacts",
                 "High upfront cost, slower return",
                 "Cancelled early may leave nothing usable",
                 "Heavy documentation, little user contact",
             ])},
            {"type": "cards", "title": "Other methodologies",
             "cards": [
                 ("RAD", "Fast prototypes improved systematically. Features before quality, heavy code reuse. Small to medium projects."),
                 ("Lean", "Cut waste, defer decisions, short cycles, fit-for-use iterations. Small teams."),
                 ("User Centred Design", "Empathetic, iterative, interdisciplinary: understand, specify, design, assess."),
             ]},
        ],
        "quiz": [
            ("Who keeps a Scrum team cohesive and resourced?", "The scrum master."),
            ("Which methodology measures progress by completed artefacts?", "Waterfall."),
            ("What is a sprint?", "A short, fixed period of work delivering an increment."),
            ("Which methodology relies heavily on reusing code?", "RAD."),
        ],
        "activity": {
            "title": "Pick the methodology",
            "time": "20 minutes",
            "format": "Small groups",
            "steps": [
                "Three projects: an NHS records system, a start-up's first app, and a charity's accessible website.",
                "Choose a methodology for each.",
                "Justify each choice with two features of the methodology.",
                "Assign team roles for one project.",
            ],
            "success": [
                "Choice fits the risk and requirements",
                "Features correctly described",
                "Roles realistic",
            ],
        },
        "exit": [
            "When is Waterfall the right choice?",
            "What does a UX designer do?",
            "Why does Agile suit changing requirements?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/03-emerging-technologies-and-skills.pptx",
        "title": "Emerging Technologies and Developing Your Skills",
        "unit": "Specialism Content Area 1",
        "spec": "1.5, 1.6",
        "pages": [ANALYSE],
        "objectives": [
            "Describe emerging technologies affecting software development.",
            "Identify your own training needs for a project.",
            "Choose ways to close a skills gap.",
        ],
        "starter": "Name a technology that did not exist when you started secondary school. How would you learn to build software for it?",
        "slides": [
            {"type": "cards", "title": "Emerging technologies",
             "cards": [
                 ("AI and VI", "Generative and conversational AI, machine learning, object recognition, computer vision."),
                 ("OT and IoT", "Operational technology and connected devices."),
                 ("Biometrics and robotics", "Identity by body features; automation."),
                 ("Cloud and data", "Cloud platforms, data lakes and data warehouses."),
                 ("Drones and 3D printing", "New physical products controlled by software."),
                 ("Networks", "5G and wider broadband."),
             ]},
            {"type": "process", "title": "Identifying and addressing training needs",
             "steps": [
                 ("Identify", "What knowledge and skills does the project need?"),
                 ("Assess", "Can you currently do the work?"),
                 ("Choose", "Coaching, on-the-job learning, self-study, forums, workshops."),
                 ("Learn and apply", "Close the gap and use it in the project."),
             ]},
        ],
        "quiz": [
            ("What is computer vision?", "AI that interprets images or video."),
            ("Give two ways to close a skills gap.", "Any two of: coaching, on-the-job learning, self-study, online forums, online workshops."),
            ("What is operational technology?", "Hardware and software that monitors and controls physical equipment."),
        ],
        "activity": {
            "title": "Skills audit",
            "time": "20 minutes",
            "format": "Individual",
            "steps": [
                "Pick a project: an IoT plant-watering app.",
                "List the skills it needs.",
                "Rate yourself on each from 1 to 5.",
                "Write a learning plan for your two weakest skills.",
            ],
            "success": [
                "Skills are specific",
                "Honest self-assessment",
                "Learning methods are realistic",
            ],
        },
        "exit": [
            "Which emerging technology excites you most?",
            "What is one skill gap you have right now?",
            "How would you find out if you are ready for a task?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/04-legal-and-ethical-development.pptx",
        "title": "Legal and Ethical Software Development",
        "unit": "Specialism Content Area 2",
        "spec": "2.1",
        "pages": [ETHICS],
        "objectives": [
            "Identify legal and regulatory requirements for a software context.",
            "Describe relevant development standards.",
            "Consider the ethical implications of software development.",
        ],
        "starter": "You are building a mobile game for under-13s with in-app purchases. What rules might apply?",
        "slides": [
            {"type": "cards", "title": "Legal and regulatory considerations",
             "cards": [
                 ("Intellectual property", "Rights, licences, copyright and patents."),
                 ("Consumers and advertising", "Consumer protection and advertising law."),
                 ("Age and gambling", "Age ratings and gambling legislation."),
                 ("Data", "Data protection, privacy and system security."),
                 ("People", "Staff responsibilities, equality and diversity."),
                 ("Territory", "Territorial restrictions on where software can be sold."),
             ]},
            {"type": "compare", "title": "Standards and ethics",
             "left": ("Development standards", [
                 "ISO/IEC/IEEE 90003:2018: software engineering guidance",
                 "W3C: web standards",
             ]),
             "right": ("Ethical considerations", [
                 "Code of conduct",
                 "Professional practice",
                 "Software licensing",
                 "Inclusion and diversity",
             ])},
        ],
        "quiz": [
            ("Which laws might apply to loot boxes in games?", "Gambling legislation and consumer protection."),
            ("What does W3C set standards for?", "The web."),
            ("Why do software licences matter?", "They set what you may legally do with code you use or distribute."),
        ],
        "activity": {
            "title": "Legal review",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Take the starter's children's game.",
                "List every legal area that applies and why.",
                "Identify two ethical concerns.",
                "Recommend design changes to comply.",
            ],
            "success": [
                "Age, data and gambling rules considered",
                "Ethics goes beyond the law",
                "Changes are practical",
            ],
        },
        "exit": [
            "Why can't you use any image you find online?",
            "What is one ethical issue in software?",
            "Why do territorial restrictions exist?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/05-identifying-and-managing-risk.pptx",
        "title": "Identifying and Managing Risk",
        "unit": "Specialism Content Area 2",
        "spec": "2.2",
        "pages": [ETHICS],
        "objectives": [
            "Identify risks in developing a software product.",
            "Assess risk by likelihood, seriousness and impact.",
            "Plan mitigation, contingency and monitoring.",
            "Justify decisions by weighing risk against reward.",
        ],
        "starter": "Launching a feature a week early could win customers, but it has not been fully tested. Would you launch?",
        "slides": [
            {"type": "cards", "title": "Risks to identify",
             "cards": [
                 ("Security", "Malicious or accidental damage to data and systems."),
                 ("Compatibility", "With other systems."),
                 ("Delivery", "Speed of development; meeting requirements and KPIs."),
                 ("Legal and ethical", "Breaking laws or harming users."),
                 ("Users", "Poor engagement or limited reach."),
             ]},
            {"type": "process", "title": "Managing risk",
             "steps": [
                 ("Identify", "List the risks for the context and market."),
                 ("Assess", "Likelihood against seriousness and impact."),
                 ("Mitigate", "Reduce the likelihood or impact."),
                 ("Contingency", "Plan what happens if it occurs."),
                 ("Monitor", "Keep checking."),
             ]},
            {"type": "bullets", "title": "Organisational policies",
             "bullets": [
                 "Backup and security policies",
                 "Confidentiality, integrity and availability (CIA)",
                 "Personnel, skills and training",
                 "Business continuity planning",
                 "Disaster recovery planning",
             ],
             "callout": "Good decisions weigh risk against reward for the specific context and market."},
        ],
        "quiz": [
            ("What two things are weighed in risk assessment?", "Likelihood and seriousness (impact)."),
            ("What is a contingency plan?", "A plan for what to do if the risk happens."),
            ("Give one organisational policy that reduces risk.", "E.g. backup, security, business continuity or disaster recovery policy."),
        ],
        "activity": {
            "title": "Risk register",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Build a risk register for a new online booking system.",
                "Include at least six risks.",
                "Score likelihood and seriousness from 1 to 5.",
                "Add mitigation, contingency and an owner for each.",
            ],
            "success": [
                "Covers security, legal and user risks",
                "Scores justified",
                "Every risk has an owner",
            ],
        },
        "exit": [
            "Which risk would stop you launching?",
            "Why monitor risks after launch?",
            "Give one reward that might justify a risk.",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/06-sources-of-knowledge-and-evaluation.pptx",
        "title": "Sources of Knowledge and Evaluating Solutions",
        "unit": "Specialism Content Area 3",
        "spec": "3.1, 3.2",
        "pages": [SOURCES],
        "objectives": [
            "Use a range of sources to find information.",
            "Judge a source on reputation, bias, evidence, cross-referencing and currency.",
            "Choose techniques to gather feedback on a software solution.",
        ],
        "starter": "You find two answers to a coding question: one on a forum from 2014, one in the official documentation. Which do you trust?",
        "slides": [
            {"type": "cards", "title": "Is the source reliable?",
             "cards": [
                 ("Reputation", "Who wrote it? Are they credible?"),
                 ("Bias", "Does the author have an angle?"),
                 ("Evidence", "What backs up the content?"),
                 ("Cross-referencing", "Do independent sources agree?"),
                 ("Currency", "When was it last updated?"),
             ],
             "notes": "Sources include search engines, wikis, blogs, academic papers, peers, forums, code comments and code repositories."},
            {"type": "compare", "title": "Gathering data to evaluate a solution",
             "left": ("Qualitative", [
                 "Verbal feedback, formal and informal",
                 "User observation with records",
                 "Focus groups",
                 "Interviews",
                 "Peer mentoring and appraisal",
             ]),
             "right": ("Quantitative", [
                 "Surveys and questionnaires",
                 "Performance data",
                 "Usage data and analytics",
             ])},
        ],
        "quiz": [
            ("Why might an old forum answer be unreliable?", "It may be out of date for the current language version."),
            ("What is triangulation?", "Checking a finding against several independent sources."),
            ("Name one qualitative and one quantitative feedback technique.", "E.g. interview; usage data."),
        ],
        "activity": {
            "title": "Evaluate an app",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Pick an app one of you built, or a college system.",
                "Write a five-question survey and an observation checklist.",
                "Test it on another group.",
                "Summarise what the data says and one improvement.",
            ],
            "success": [
                "Mix of qualitative and quantitative",
                "Questions are unbiased",
                "Improvement follows from the data",
            ],
        },
        "exit": [
            "Which source do you use most, and how reliable is it?",
            "Why use a focus group?",
            "What does usage data tell you that interviews don't?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/07-design-approaches.pptx",
        "title": "Software Design Approaches",
        "unit": "Specialism Content Area 4",
        "spec": "4.1",
        "pages": [DESIGN],
        "objectives": [
            "Describe function-oriented and object-oriented design.",
            "Describe data model design.",
            "Explain test-driven and behaviour-driven development.",
            "Describe functional design and choose an approach for a project.",
        ],
        "starter": "Would you design a banking system and a physics game the same way? What would differ?",
        "slides": [
            {"type": "cards", "title": "Design approaches (1)",
             "cards": [
                 ("Function-oriented (top-down)", "Break the system into functions; data flow diagrams show how data changes. Divide and conquer."),
                 ("Object-oriented", "Classes, objects and methods. Encapsulation, abstraction, polymorphism, inheritance. Creational, structural and behavioural patterns."),
                 ("Data model design", "Conceptual, logical, physical, hierarchical and relational models, using E-R models and UML."),
             ]},
            {"type": "process", "title": "Test-driven development (TDD)",
             "steps": [
                 ("Add a test", "Define what the feature should do."),
                 ("Run tests", "The new test fails."),
                 ("Write code", "Just enough to pass."),
                 ("Refactor", "Run tests and tidy the code."),
                 ("Repeat", "Next feature."),
             ]},
            {"type": "compare", "title": "BDD and functional design",
             "left": ("Behaviour-driven development", [
                 "Required behaviour specified before coding",
                 "Behaviours must have business value",
                 "Title, narrative, acceptance criteria",
             ]),
             "right": ("Functional design", [
                 "Modules each perform one function",
                 "Recursion and closures",
                 "First-class, higher-order and anonymous functions",
                 "Currying",
             ])},
        ],
        "quiz": [
            ("What are the four characteristics of OOP?", "Encapsulation, data abstraction, polymorphism, inheritance."),
            ("In TDD, what comes first: the test or the code?", "The test."),
            ("What is a higher-order function?", "A function that takes or returns another function."),
            ("Which tools support data model design?", "E-R models and UML."),
        ],
        "activity": {
            "title": "TDD kata",
            "time": "30 minutes",
            "format": "Pairs, in Python",
            "steps": [
                "Build a function that grades a mark: A, B, C or U.",
                "Write one failing test first.",
                "Write just enough code to pass it.",
                "Repeat until every boundary is tested, then refactor.",
            ],
            "success": [
                "Tests written before code",
                "Boundaries tested",
                "Code refactored with tests still passing",
            ],
        },
        "exit": [
            "Which design approach suits a game with many similar characters?",
            "Why does TDD reduce bugs?",
            "What is inheritance?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/08-platforms-version-control-and-collaboration.pptx",
        "title": "Platforms, Version Control and Collaboration",
        "unit": "Specialism Content Areas 4 and 5",
        "spec": "4.2, 5.1, 5.2",
        "pages": [DESIGN, COLLAB],
        "objectives": [
            "Describe development platform features from coding to deployment.",
            "Compare proprietary and open-source platforms, GitFlow and GitHubFlow.",
            "Explain the reasons for collaborative techniques and code reviews.",
            "Select collaborative technologies.",
        ],
        "starter": "Two developers edit the same file at the same time and both save. What happens without version control?",
        "slides": [
            {"type": "compare", "title": "Development platforms",
             "left": ("Features", [
                 "Coding and repositories",
                 "Branching",
                 "Building and testing",
                 "Deployment",
                 "Proprietary or open source",
             ]),
             "right": ("Choosing a platform", [
                 "Target audience and budget",
                 "Technical features, security, reliability",
                 "Staff skills and training",
                 "Speed of development and updates",
                 "Performance and compatibility",
             ])},
            {"type": "compare", "title": "Workflow management",
             "left": ("GitFlow", [
                 "Long-lived main and develop branches",
                 "Feature, release and hotfix branches",
                 "Suits scheduled releases",
             ]),
             "right": ("GitHubFlow", [
                 "One main branch, always deployable",
                 "Short feature branches and pull requests",
                 "Suits continuous deployment",
             ])},
            {"type": "cards", "title": "Why collaborate?",
             "cards": [
                 ("Speed", "Work happens in parallel."),
                 ("Communication", "Everyone stays informed."),
                 ("Knowledge", "Skills and knowledge are shared."),
                 ("Code reviews", "Paired programming, informal walkthroughs, formal inspections."),
             ],
             "notes": "Students should also judge when working independently is more appropriate."},
            {"type": "table", "title": "Collaborative technologies",
             "header": ["Category", "Examples"],
             "widths": [2.6, 6],
             "rows": [
                 ["Communication", "Email, instant messaging"],
                 ["Resource management", "Cloud storage, backup, synchronisation"],
                 ["Knowledge sharing", "Collaboration hubs, wikis, forums, news sites"],
                 ["Documentation", "For technical and non-technical audiences"],
                 ["Development", "Code collaboration, version control, source control, IDEs"],
             ]},
        ],
        "quiz": [
            ("What is a branch?", "A separate line of development in a repository."),
            ("Which workflow keeps one always-deployable main branch?", "GitHubFlow."),
            ("Name three types of code review.", "Paired programming, informal walkthroughs, formal inspections."),
            ("What is the difference between version control and source control?", "Version control tracks changes to any files over time; source control manages source code specifically."),
        ],
        "activity": {
            "title": "Branch, merge, review",
            "time": "35 minutes",
            "format": "Pairs, with Git",
            "steps": [
                "Create a repository and commit a small program.",
                "Each partner makes a feature branch and changes a different function.",
                "Open a pull request and review each other's code.",
                "Merge both branches and resolve any conflict.",
            ],
            "success": [
                "Meaningful commit messages",
                "Review comments are constructive",
                "Conflict resolved correctly",
            ],
        },
        "exit": [
            "When is working alone better than pairing?",
            "Why write clear commit messages?",
            "Which workflow suits a website that deploys daily?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/09-ux-and-ui-design.pptx",
        "title": "UX and UI Design",
        "unit": "Specialism Content Areas 4 and 6",
        "spec": "4.3 (UX and UI), 6.2",
        "pages": [DESIGN, IMPL],
        "objectives": [
            "Apply UX design principles.",
            "Use wireframes, style guides and clickable prototypes.",
            "Choose UI features and techniques.",
            "Make design decisions for devices, users and accessibility.",
        ],
        "starter": "Think of an app that annoys you. What exactly makes it annoying to use?",
        "slides": [
            {"type": "cards", "title": "UX design principles",
             "cards": [
                 ("Consistency", "Intuitive, pleasing and on-brand."),
                 ("Information hierarchy", "Easier navigation."),
                 ("Visual hierarchy", "Important content stands out."),
                 ("Confirmation", "Users know what they did and its effect."),
                 ("User control", "Efficient navigation and easy error correction."),
                 ("Accessibility", "Works for a wide range of users."),
             ],
             "notes": "UI design tools: wireframes, style guides and clickable prototypes."},
            {"type": "compare", "title": "UI features and techniques",
             "left": ("Features", [
                 "Images and animation",
                 "Audio and visual effects",
                 "Input and feedback: text, graphics, audio, haptic",
                 "Dashboards, graphs, data presentation",
             ]),
             "right": ("Techniques", [
                 "Layout grids and use of space",
                 "Fonts, letter and line spacing, justification",
                 "Colour and contrast",
                 "Input focus and hover controls",
             ])},
            {"type": "cards", "title": "Design decisions",
             "cards": [
                 ("Platform", "Browser support and target device."),
                 ("Users", "Characteristics, accessibility and input method: voice, text, touch, mouse."),
                 ("Bandwidth", "What users can download."),
                 ("Brand", "Style and branding."),
             ]},
        ],
        "quiz": [
            ("What is a wireframe?", "A simple layout sketch of a screen without final styling."),
            ("Which UX principle means users know what their action did?", "Confirmation."),
            ("Why does contrast matter?", "Low contrast makes text hard to read, especially for visually impaired users."),
            ("Give one example of haptic feedback.", "A phone vibrating when you press a button."),
        ],
        "activity": {
            "title": "Wireframe and critique",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Wireframe three screens for a revision quiz app.",
                "Annotate which UX principle each design choice supports.",
                "Swap and critique another pair's wireframes for accessibility.",
                "Improve one screen based on the feedback.",
            ],
            "success": [
                "Clear visual hierarchy",
                "Accessibility considered",
                "Feedback acted on",
            ],
        },
        "exit": [
            "Name one UX principle your favourite app uses well.",
            "Why design for touch and mouse differently?",
            "What is a style guide for?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/10-designing-data-assets-and-integration.pptx",
        "title": "Designing Data, Assets and Integration",
        "unit": "Specialism Content Area 4",
        "spec": "4.3 (program, assets, platforms, databases, networks)",
        "pages": [DESIGN],
        "objectives": [
            "Apply program design conventions and CMS features.",
            "Select assets and use AI legally and ethically.",
            "Design a database using a data dictionary, ERD and normalisation.",
            "Plan target platforms and network integration points.",
        ],
        "starter": "In a multiplayer game, what must happen on your device and what must happen on the server?",
        "slides": [
            {"type": "cards", "title": "Program design and CMS",
             "cards": [
                 ("Design conventions", "Pre-defined code, BCS flowcharts, pseudocode, control structures, data types, validation, data structures."),
                 ("CMS features", "SEO, page management, social media, analytics, workflow, publishing controls, security, versioning, APIs, multilingual."),
             ]},
            {"type": "cards", "title": "Assets and AI",
             "cards": [
                 ("Asset choices", "File type, size, compression, streaming and encoding, metadata, quality."),
                 ("Constraints", "Available bandwidth, storage and target platform."),
                 ("Using AI", "Check licences and ownership; work legally and ethically."),
             ]},
            {"type": "process", "title": "Designing a database",
             "steps": [
                 ("Purpose", "User management, e-commerce, diagnostics, performance."),
                 ("Data dictionary", "Every field, type and rule."),
                 ("ERD", "Entities and relationships."),
                 ("Normalise", "To third normal form."),
             ]},
            {"type": "cards", "title": "Platforms and integration",
             "cards": [
                 ("Target platforms", "OS, file system, physical or virtual servers, language stack, mobile or web."),
                 ("Local or remote", "What runs on the device, what runs on the server."),
                 ("Connections", "How data moves, e.g. remote system calls; system boundaries."),
                 ("External systems", "Third-party feeds such as sports data."),
             ]},
        ],
        "quiz": [
            ("What is a data dictionary?", "A document describing every field, its type and rules."),
            ("What does normalisation reduce?", "Data redundancy (duplication)."),
            ("Give one factor when selecting a video asset.", "E.g. file size, compression, bandwidth, quality."),
            ("What is a system boundary?", "Where your system ends and external systems begin."),
        ],
        "activity": {
            "title": "Design a shop database",
            "time": "35 minutes",
            "format": "Pairs",
            "steps": [
                "A small online shop sells products to customers who place orders.",
                "Write a data dictionary for three tables.",
                "Draw the ERD.",
                "Check it is in third normal form and explain why.",
            ],
            "success": [
                "Primary and foreign keys shown",
                "Relationships correct",
                "No repeated data",
            ],
        },
        "exit": [
            "Why process some data locally?",
            "What is a foreign key?",
            "Name one CMS feature and why it matters.",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/11-languages-ci-cd-and-good-practice.pptx",
        "title": "Languages, CI/CD and Good Practice",
        "unit": "Specialism Content Area 6",
        "spec": "6.1",
        "pages": [IMPL],
        "objectives": [
            "Select at least two languages for front-end and back-end work.",
            "Use tools, APIs, packages and libraries to add functionality.",
            "Describe the stages of a CI/CD pipeline.",
            "Apply coding conventions and the 12-factor principles.",
        ],
        "starter": "A website has a page you see and a database you don't. Which languages might build each part?",
        "slides": [
            {"type": "table", "title": "Languages in the specification",
             "header": ["Language", "Typical use"],
             "widths": [2, 6.6],
             "rows": [
                 ["Python 3.10+", "Back-end logic, data processing, scripting"],
                 ["C#", "Desktop, games and back-end services"],
                 ["SQL", "Querying and changing databases"],
                 ["JavaScript", "Interactive front ends, and back ends with Node"],
                 ["PHP", "Server-side web pages"],
             ],
             "caption": "Tools and libraries add features: dynamic content, forms, files, cookies, layouts, networking, security, containers."},
            {"type": "process", "title": "CI/CD pipeline",
             "steps": [
                 ("Source control", "Code in a repository."),
                 ("Build", "Automated builds."),
                 ("Unit tests", "Automated testing."),
                 ("Deploy", "Automated deployment."),
                 ("Monitor", "Watch it in production."),
             ],
             "notes": "Packaging: organise front and back end into one product, e.g. HTML, CSS and frameworks, or a single executable."},
            {"type": "cards", "title": "Coding conventions",
             "cards": [
                 ("Naming", "Consistent, meaningful names."),
                 ("Comments", "Annotations that explain why."),
                 ("Modularisation", "Small, focused functions and modules."),
                 ("Structure", "Consistent indentation."),
                 ("Version control", "Commit early and often."),
             ]},
            {"type": "table", "title": "The 12-factor app (highlights)",
             "header": ["Factor", "Meaning"],
             "widths": [2.6, 6],
             "rows": [
                 ["Codebase", "One codebase in revision control, many deploys"],
                 ["Dependencies", "Declare and isolate them explicitly"],
                 ["Config", "Store configuration in the environment"],
                 ["Build, release, run", "Keep the stages strictly separate"],
                 ["Processes", "Run as stateless processes"],
                 ["Dev/prod parity", "Keep development and production alike"],
                 ["Logs", "Treat logs as event streams"],
             ],
             "notes": "The other five: backing services as attached resources, port binding, scale via processes, fast startup and graceful shutdown, admin tasks as one-off processes."},
        ],
        "quiz": [
            ("Which language is used to query databases?", "SQL."),
            ("Name the five CI/CD stages.", "Source control, build automation, unit test automation, deployment automation, monitoring."),
            ("Where should configuration be stored in a 12-factor app?", "In the environment."),
            ("Why keep development and production similar?", "So code that works in development also works in production."),
        ],
        "activity": {
            "title": "Two-language mini app",
            "time": "45 minutes",
            "format": "Pairs",
            "steps": [
                "Build a Python script that stores feedback in an SQLite database using SQL.",
                "Move the database file name into an environment variable.",
                "Write two unit tests.",
                "Sketch how a CI pipeline would run your tests on every commit.",
            ],
            "success": [
                "Two languages used correctly",
                "Config not hard-coded",
                "Tests pass",
            ],
        },
        "exit": [
            "Which two languages would you pick for a booking website?",
            "Why automate tests in CI?",
            "Why keep secrets out of code?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/12-data-connections-and-deployment.pptx",
        "title": "Connecting to Data and Deploying Software",
        "unit": "Specialism Content Area 6",
        "spec": "6.3, 6.4",
        "pages": [IMPL],
        "objectives": [
            "Connect code to data sources using APIs, JDBC and ODBC.",
            "Extract, store, update and delete data.",
            "Select a deployment method for a project.",
        ],
        "starter": "A weather app shows today's forecast. Where does that data come from, and how does the app get it?",
        "slides": [
            {"type": "table", "title": "Connecting to data",
             "header": ["Method", "Key parts"],
             "widths": [1.8, 6.8],
             "rows": [
                 ["API", "Request types and methods (GET, POST...), endpoints, parsing responses, API keys"],
                 ["JDBC", "Core API, driver manager, connection, statement, prepared statement, result set, SQL"],
                 ["ODBC", "Application, driver manager, driver, data source, connection details and credentials"],
             ],
             "caption": "Choose the data source and connection method that suits the context, not just the one you know."},
            {"type": "cards", "title": "Working with data",
             "cards": [
                 ("Create", "Store new records."),
                 ("Read", "Extract and display data."),
                 ("Update", "Change existing records."),
                 ("Delete", "Remove records safely."),
             ]},
            {"type": "table", "title": "Deployment methods",
             "header": ["Method", "Suits"],
             "widths": [2.6, 6],
             "rows": [
                 ["Local installation", "Single users, offline tools"],
                 ["Network / server installation", "Organisations managing many PCs"],
                 ["Mobile platforms", "App store distribution"],
                 ["Web and cloud platforms", "Anyone with a browser; easy updates"],
                 ["Containers and scheduling platforms", "Consistent, scalable deployment"],
             ]},
        ],
        "quiz": [
            ("What is an API endpoint?", "A specific URL where an API receives requests."),
            ("What does a prepared statement protect against?", "SQL injection."),
            ("What does ODBC stand for?", "Open Database Connectivity."),
            ("Why use containers for deployment?", "The app runs the same way everywhere and scales easily."),
        ],
        "activity": {
            "title": "Call a real API",
            "time": "30 minutes",
            "format": "Pairs, in Python",
            "steps": [
                "Use the requests library to call a free public API chosen by your teacher.",
                "Parse the JSON response and display three values.",
                "Handle a failed request with a clear message.",
                "Recommend a deployment method for your tool.",
            ],
            "success": [
                "Data parsed correctly",
                "Errors handled",
                "Deployment choice justified",
            ],
        },
        "exit": [
            "Why keep API keys secret?",
            "When would you choose a mobile deployment?",
            "What does CRUD stand for?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/13-testing-a-software-solution.pptx",
        "title": "Testing a Software Solution",
        "unit": "Specialism Content Area 7",
        "spec": "7.1, 7.2, 7.3",
        "pages": [TESTING],
        "objectives": [
            "Select functional, non-functional, front-end and security testing.",
            "Use acceptance, alpha, beta, closed box and open box testing.",
            "Design tests with the full range of test data.",
            "Update a test plan with results and regression tests.",
        ],
        "starter": "Your website works on your laptop. List every other situation you should test it in.",
        "slides": [
            {"type": "cards", "title": "Types of testing",
             "cards": [
                 ("Functional", "Unit, smoke, integration and system testing."),
                 ("Non-functional", "Availability, compatibility, configuration and load testing."),
                 ("Front-end", "Performance, browsers, OS, rendering, loading times, responsiveness."),
                 ("Security", "Vulnerability scanning, static, dynamic and integration analysis."),
             ]},
            {"type": "table", "title": "Testing techniques",
             "header": ["Technique", "What it means"],
             "widths": [2.4, 6.2],
             "rows": [
                 ["Acceptance", "Does it meet the client's requirements?"],
                 ["Alpha", "Early internal testing"],
                 ["Beta", "Limited real, external users before release"],
                 ["Closed box (black box)", "Inputs and outputs only, no code knowledge"],
                 ["Open box (white box)", "Tests based on the code's structure"],
             ],
             "caption": "Tests can be manual or automatic, including AI-assisted tools."},
            {"type": "cards", "title": "Test data",
             "cards": [
                 ("Valid", "Normal, accepted data."),
                 ("Invalid", "Should be rejected."),
                 ("Valid extreme", "At the edge but allowed."),
                 ("Invalid extreme", "Just outside the limit."),
                 ("Erroneous", "Wrong type entirely."),
             ],
             "notes": "Each test also needs a purpose, pre-requisites and an expected result. Afterwards, record actual results, changes made, and any re-tests or regression tests."},
        ],
        "quiz": [
            ("What is smoke testing?", "A quick check that the main functions work before deeper testing."),
            ("What is the difference between alpha and beta testing?", "Alpha is internal; beta uses a limited group of real external users."),
            ("For a range 1 to 100, give valid extreme and invalid extreme values.", "Valid extreme: 1 or 100. Invalid extreme: 0 or 101."),
            ("What is static analysis?", "Checking code for problems without running it."),
        ],
        "activity": {
            "title": "Full test plan",
            "time": "35 minutes",
            "format": "Pairs",
            "steps": [
                "Choose a feature from your own project.",
                "Write tests using all five test data types.",
                "Add one front-end and one security test.",
                "Run them, record results and plan regression tests.",
            ],
            "success": [
                "Pre-requisites stated",
                "All data types used",
                "Regression testing planned",
            ],
        },
        "exit": [
            "Why run beta tests with real users?",
            "What is open box testing?",
            "When should regression tests run?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/14-change-maintain-and-support.pptx",
        "title": "Change, Maintain and Support Software",
        "unit": "Specialism Content Area 8",
        "spec": "8.1 to 8.4",
        "pages": [CHANGE],
        "objectives": [
            "Explain why digital products change.",
            "Describe the software change management process.",
            "Apply good coding principles when maintaining code in a team.",
            "Communicate with users and resolve their issues systematically.",
        ],
        "starter": "Why does your phone keep asking you to update apps that seem to work fine?",
        "slides": [
            {"type": "cards", "title": "Why products change",
             "cards": [
                 ("Preventing", "Foreseeable issues: new regulations, new technology, business changes."),
                 ("Correcting", "Unforeseen errors: zero-days, attacks, data corruption, failures."),
                 ("Iterating", "Staying relevant: feedback, new tech, competition, efficiency, future-proofing."),
             ]},
            {"type": "process", "title": "Software change management",
             "steps": [
                 ("Identify", "Issues from feedback or review."),
                 ("Document", "Record the changes."),
                 ("Communicate", "To technical and non-technical audiences."),
                 ("Plan", "What must change."),
                 ("Schedule", "When it will change."),
                 ("Regression test", "Check nothing else broke."),
                 ("Release", "Planned or emergency."),
             ]},
            {"type": "compare", "title": "Maintaining code and supporting users",
             "left": ("Maintaining code in a team", [
                 "Separate code into modules",
                 "Write readable code",
                 "Follow agreed conventions",
                 "Comment helpfully",
                 "Keep change logs up to date",
             ]),
             "right": ("Communicating with users", [
                 "Face to face and remote calls",
                 "Blogs, reports, release notes, guides, FAQs",
                 "Demonstrations, screencasts, narration",
                 "Machine-readable API contracts",
             ])},
            {"type": "process", "title": "Resolving user issues",
             "steps": [
                 ("Replicate", "Identify or reproduce the issue."),
                 ("Investigate", "User, system or application error, or a breach?"),
                 ("Fix and test", "Make the change, confirm it stays fixed with no new issues."),
                 ("Communicate", "Tell stakeholders how and when."),
                 ("Learn", "Document the lessons."),
             ]},
        ],
        "quiz": [
            ("Fixing a zero-day vulnerability is which type of change?", "Correcting."),
            ("Why is regression testing part of change management?", "To make sure the change hasn't broken other features."),
            ("Name two written formats for communicating with users.", "Any two of: blogs, reports, technical documentation, release notes, user guides, FAQs."),
            ("What is the first step in resolving a user issue?", "Identify or replicate it."),
        ],
        "activity": {
            "title": "Release notes and support",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher gives you a bug report and a code change.",
                "Replicate the bug, fix it and add a change log entry.",
                "Write release notes for non-technical users.",
                "Write a short technical note for other developers.",
            ],
            "success": [
                "Bug replicated before fixing",
                "Change log is clear",
                "Tone matches each audience",
            ],
        },
        "exit": [
            "Give an example of an iterating change.",
            "Why keep a change log?",
            "How would you explain a fix to a non-technical user?",
        ],
    },
]
